### PR TITLE
Updat to test_bonds.py that accepts N as acceptor

### PR DESCRIPTION
**Pull request by gkiss**

### CODE REVIEW

**Comment by swails** [comment]
This isn't going to "fix" the CI results for #679.  Is there any reason you didn't just push this to the branch you submitted #679 from?

**Comment by kyleabeauchamp** [comment]
I think he directly edited the files from the Github HTML editor.

**Comment by gkiss** [comment]
Sorry guys. Still getting my feet wet with GitHub

**Comment by kyleabeauchamp** [comment]
No worries

**Pull request merged**
