### PR TITLE
Update syntax for GSD reader/writer

### PR DESCRIPTION
**Pull request by daico007**
Address #1825, update syntax in `gsd.py` to match with the latest GSD 3 open syntax (https://gsd.readthedocs.io/en/stable/python-module-gsd.hoomd.html).

### CODE REVIEW

**Review by natsukium — COMMENTED** [review]
Thanks for your investigation.
Could you please patch line 122 in the same way?
You can run pytest to see if you fixed it correctly.

Also, I think we need to replace `gsd.hoomd.Snapshot` with `gsd.hoomd.Frame`.
See https://gsd.readthedocs.io/en/stable/changes.html#id5.

**Comment by mattwthompson** [comment]
Tests are passing, which is great, and the code looks fine, but maybe there's some stuff that isn't covered by tests?

Could you run a [local report](https://coverage.readthedocs.io/en/7.3.2/#quick-start) and let us know how much of the HOOMD-related submodules are covered by tests?

**Comment by natsukium** [comment]
> Tests are passing, which is great, and the code looks fine, but maybe there's some stuff that isn't covered by tests?

Because we use `gsd == 2.9.0` on github actions, but this PR is for `gsd >= 3`.
https://github.com/mdtraj/mdtraj/actions/runs/6657489620/job/18149382762?pr=1826#step:5:53

**Comment by mattwthompson** [comment]
Good catch! I totally missed that. @daico007 could you update the test environment to use GSD 3?

Unless there is a compelling need to maintain backwards compatibility with future versions, I think the release containing this change should just work with just GSD 3

**Comment by daico007** [comment]
Gotcha! Thank you y'all for the feedback! I will try to have those changes in tomorrow.

**Comment by daico007** [comment]
Final commits passed all the gsd test locally

**Review by mattwthompson — APPROVED** [review]
It looks like the only relevant API change here was the difference in supported file modes?

If so, that would work with GSD v2 so maybe we can just have `gsd =2,3` in deployment

**Comment by daico007** [comment]
The `gsd.hoomd.Frame` was introduced in gsd v2.8.0 (https://gsd.readthedocs.io/en/stable/changes.html#id5), so that's we will can only support that version forward

**Comment by mattwthompson** [comment]
Either is fine - could you merge upstream back in? I reverted the coverage stuff since it wasn't working and I don't have the time to invest into fixing it.

**Comment by daico007** [comment]
Done

**Pull request merged**
