### PR TITLE
Remove HTML Trajectory Viewer

### PR DESCRIPTION
**Pull request by cxhernandez**
re: https://github.com/mdtraj/mdtraj/issues/1199

### CODE REVIEW

**Comment by mpharrigan** [comment]
Test failure is relevant. Can you remove the examples as well

**Comment by rmcgibbo** [comment]
Did this go through a deprecation cycle? Should we remove it now or wait for the next release?

**Comment by mpharrigan** [comment]
@cxhernandez can address more, but I think it's been broken for a while

**Comment by mpharrigan** [comment]
https://github.com/mdtraj/mdtraj/issues/1022
https://github.com/mdtraj/mdtraj/issues/1068

**Comment by ctk3b** [comment]
Looks like it's been broken under some conditions for at least the previous 2 releases.

**Comment by rmcgibbo** [comment]
Got it. I'm +1 then.

**Comment by cxhernandez** [comment]
@mpharrigan: Ah, I missed those!

**Comment by mpharrigan** [comment]
Some overzealousness with the conda dependency removals

**Comment by cxhernandez** [comment]
> Some overzealousness with the conda dependency removals

That's why it has its own commit 😋

**Comment by cxhernandez** [comment]
what's up with macOS?

**Comment by mpharrigan** [comment]
look at the error message. `docs/_static/trajectory-html` symlink needs to be removed

**Pull request merged**
