### PR TITLE
test mdconvert for NetCDF4 backend

### PR DESCRIPTION
**Pull request by xiki-tempula**
Try to see if I could reproduce the issue #1939

### CODE REVIEW

**Comment by mattwthompson** [comment]
Please keep `mdconvert` tests in `tests/test_mdconvert.py`

**Comment by xiki-tempula** [comment]
@mattwthompson Moved. Do you mind kick up the workflow?

**Comment by mattwthompson** [comment]
Is there a way to authorize your changes so you can continue to iterate without us needing to click? I know commits from anybody who has committed to the repo doesn't need this click, but it also seems obtuse to need to add you to an organization role, `CODEOWNERS` file, or similar.

I get why GitHub defaults to this behavior for public forks, but you're not just some random stranger here.

**Comment by xiki-tempula** [comment]
Thanks. Sorry, I'm just being lazy and just change it on the fly in website so it takes a couple iterations. I kind of opened this branch to demonstrate that this is a bug. I tried to fix it but cannot figure out why netcdf.Dataset doesn't take format keyword. Do you mind take over and try to see if you could fix the issue? I think the current test shall definitely reproduce the bug.

**Comment by xiki-tempula** [comment]
This problem will be fixed by 1.10.1 release

**Pull request closed without merging**
