### PR TITLE
handle a single frame being passed to sparta+

### PR DESCRIPTION
**Pull request by smsaladi**
See #1245

### CODE REVIEW

**Comment by mpharrigan** [comment]
hmm this looks like it breaks the tests

**Comment by smsaladi** [comment]
Interesting... will investigate

**Comment by mpharrigan** [comment]
actually this test failure is showing up in other PRs too #1247

**Comment by mpharrigan** [comment]
```
ERROR: mdtraj.tests.test_nmr.test_spartaplus

----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda3/conda-bld/mdtraj_1490338309326/_t_env/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda3/conda-bld/mdtraj_1490338309326/_t_env/lib/python3.5/site-packages/numpy/testing/decorators.py", line 147, in skipper_func
    return f(*args, **kwargs)
  File "/home/travis/miniconda3/conda-bld/mdtraj_1490338309326/_t_env/lib/python3.5/site-packages/mdtraj/tests/test_nmr.py", line 11, in test_spartaplus
    result = md.chemical_shifts_spartaplus(t)
  File "/home/travis/miniconda3/conda-bld/mdtraj_1490338309326/_t_env/lib/python3.5/site-packages/mdtraj/nmr/shift_wrappers.py", line 298, in chemical_shifts_spartaplus
    lines_to_skip = _get_lines_to_skip("trj0_pred.tab")
  File "/home/travis/miniconda3/conda-bld/mdtraj_1490338309326/_t_env/lib/python3.5/site-packages/mdtraj/nmr/shift_wrappers.py", line 235, in _get_lines_to_skip
    handle = open(filename)
FileNotFoundError: [Errno 2] No such file or directory: 'trj0_pred.tab'
```

**Pull request closed without merging**
