### PR TITLE
added chi5 angle computation

### PR DESCRIPTION
**Pull request by marscher**
sometimes one is literally interested in all dihedrals, which includes chi5 as well. cc @giopina

### CODE REVIEW

**Comment by marscher** [comment]
ERROR: mdtraj.tests.test_nmr.test_shiftx2

**Comment by marscher** [comment]
This is pretty much unrelated to my changes, right?

**Comment by mpharrigan** [comment]
Yes, that's a known failure. Thanks for this! lgtm

**Comment by marscher** [comment]
I think it is assumed by the indices getter that CHI_N_ATOMS is a 2d list. Sorry for that. BTW the dihedral test case depends on PyMOL, is this installed during the test session?

**Pull request merged**
