### PR TITLE
Add CONECT bonds based on last model, not first

### LINKED ISSUE #977: Bonds based on CONECT records are not added for multi-model files
CONECT records are required to be after the last ENDMDL, hence [pdbstructure.py](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/pdb/pdbstructure.py#L203-L212) only fills `connects` for the last model. 

However, [pdbfile.py] (https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/pdb/pdbfile.py#L524) appends bonds based on the `connects` from the first model. 

Simply change [the pdbfile.py line] (https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/pdb/pdbfile.py#L524) to:
``` python
for connect in pdb.models[-1].connects:
```
works. Should I PR this revolutionary modification?

### PR DESCRIPTION
**Pull request by rafwiewiora**
Closes #977.

### CODE REVIEW

**Comment by mpharrigan** [comment]
The test failure looks relevant. Can you add a test case for #977 ?

**Comment by rmcgibbo** [comment]
```
======================================================================
FAIL: mdtraj.formats.pdb.tests.test_pdb.test_1vii_solvated_with_ligand
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda3/envs/_test/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda3/envs/_test/lib/python2.7/site-packages/mdtraj/formats/pdb/tests/test_pdb.py", line 108, in test_1vii_solvated_with_ligand
    eq(len(list(traj.top.bonds)), 5124)
  File "/home/travis/miniconda3/envs/_test/lib/python2.7/site-packages/mdtraj/testing/testing.py", line 134, in eq
    eq_(long(o1), long(o2))
AssertionError: 5156L != 5124L
----------------------------------------------------------------------
```

**Comment by rafwiewiora** [comment]
Alright, 5124 is not correct - that didn't consider the CONECT bonds. Gonna change to 5156. Any point also adding a test [here] (https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/pdb/tests/test_pdb.py#L106) for whether the ligand bonds are added to topology, like:

```python
eq(len([bond for bond in traj.top.bonds if bond[0].residue.name == 'LIG']), 32)
```
?

**Comment by rmcgibbo** [comment]
Sure. Always :1: for more tests.

**Comment by rmcgibbo** [comment]
I think @mpharrigan is about to make a release (in like 10 minutes). Is it a problem if this doesn't get picked up until the subsequent release?

**Comment by rafwiewiora** [comment]
Totally fine!

**Comment by rafwiewiora** [comment]
Tests fixed, what's the deal with the AppVeyor fail? Doesn't look relevant.

**Comment by rmcgibbo** [comment]
I haven't debugged the Appveyor issue. I think there is a 32 vs. 64 bit integer size bug in the DSSP code that's causing a segfault, but I don't know for sure.

**Comment by rafwiewiora** [comment]
Alright cool

**Comment by rmcgibbo** [comment]
I opened #989 to track the windows issue.

**Pull request merged**
