### PR TITLE
Implement generic C code paths for non-accelerated architectures.

### PR DESCRIPTION
**Pull request by tonigi**
This should enable compilation on ppc64le (at least). 

The setup code now includes a check for SSE2 availability. If neither SSE nor NEON intrinsics are available, the generic C version is used. It can also be enforced anyway at compile time setting env `MDTRAJ_BUILD_DISABLE_INTRINSICS=1`. 

On ppc64le, all the tests seem to pass, with some differences likely due to floating point tolerance. 

Work done by @org305 . 

Relevant issues: https://github.com/mdtraj/mdtraj/issues/888   https://github.com/mdtraj/mdtraj/issues/1541 https://github.com/mdtraj/mdtraj/issues/1432

It may make sense to CI on ppc64le (likely best done in conda feedstock).

### CODE REVIEW

**Comment by rmcgibbo** [comment]
Very cool.

How about adding some tests on x86 that compile in this new generic code and also the specialized code and make sure that the numerics are the same?

I'm worried that if we add code that's only compiled on ppc64le, it's going to bitrot since very few of the developers are interested and have access to in those machines.

**Comment by tonigi** [comment]
Hmm... would it make sense to run the full pytest suite in CI?  If so, the CI could build packages and run tests for cases (i.e. with and without `MDTRAJ_BUILD_DISABLE_INTRINSICS`).

**Comment by rmcgibbo** [comment]
Doubling the total test load just for ppc64le seems like perhaps a bit much, but maybe certain tests that actually use these features could be tagged to run with both DISABLE_INTRINSICS and without.

**Comment by tonigi** [comment]
To clarify: MDTRAJ_BUILD_DISABLE_INTRINSICS only affects build behaviour.  Depending on that variable and supported intrinsics in the compiler, only one of the [generic, sse, neon] version is compiled. So currently it's not possible to test  both code versions with one build. 

Here's two options forward, in my opinion (I apologize if I misunderstood mdtraj's CI strategy):
 * in CI, make a non-accelerated build on x86, run just a few tests, then discard the built object - this gives some confidence that the results will be similar in ppc
 * and/or let conda-forge do an actual ppc build, and test it thoroughly
 
The existing tests seem rather stringent to me, and should catch differences in results, should they arise. How is testing handled for the ARM/NEON version?

I understand the risk of bitrot and that supporting minority architectures is undesirable, but lacking mdtraj on some HPC installations (where OpenMM runs nicely) feels like a bit of a "missing piece" that gets in the way.

**Comment by rmcgibbo** [comment]
Yep, I think I understand.

From my perspective, the ideal solution for CI would probably be to add a “job” the to the CI build matrix that compiles in generic mode, but this job should probably only run “relevant” tests, like the ones that use the geometry and RMSD modules.

For aarch64, there are currently no tests on the CI, so I recognize that I might be holding ppc64le to a slightly higher standard. Sorry. To some extent that’s because people own personal aarch64 macs so I trust that the tests suit is getting some exercise there.

**Comment by tonigi** [comment]
Thanks! Something like the above commit?  (It's not a perfect test, because intrinsics dependencies can still sneak in e.g. from system libraries, but should be good enough)

**Comment by rmcgibbo** [comment]
Something like https://github.com/giorginolab/mdtraj/pull/3 is what I have in mind.

**Comment by tonigi** [comment]
Any idea on this? There is a [segfault](https://github.com/giorginolab/mdtraj/runs/5598510332?check_suite_focus=true#step:5:2598) deep in image_molecules C interface, which seems unrelated to the changes. Possibly a Cython+nix version thing.

**Comment by rmcgibbo** [comment]
I think the same thing happened in this PR and then went away after it was merged: https://github.com/mdtraj/mdtraj/pull/1718

**Comment by rmcgibbo** [comment]
Eh, let's merge and roll the dice.

**Comment by tonigi** [comment]
Apparently it worked. My hunch is that sometimes nix packs a subtly corrupt version, and the failure remains until a new artifact is built. Diffing  the logs was not especially enlightening. Thanks for merging though!

**Pull request merged**
