### PR TITLE
MAINT: Increase minimum required python version to 2.7

### PR DESCRIPTION
**Pull request by rmcgibbo**
Discussed a little bit in #810.

### CODE REVIEW

**Comment by mpharrigan** [comment]
+1

**Comment by rmcgibbo** [comment]
Test failure is

```
======================================================================
ERROR: mdtraj.tests.test_nmr.test_spartaplus
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/_test/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/miniconda/envs/_test/lib/python3.4/site-packages/numpy/testing/decorators.py", line 146, in skipper_func
    return f(*args, **kwargs)
  File "/home/travis/miniconda/envs/_test/lib/python3.4/site-packages/mdtraj/tests/test_nmr.py", line 10, in test_spartaplus
    result = md.chemical_shifts_spartaplus(t)
  File "/home/travis/miniconda/envs/_test/lib/python3.4/site-packages/mdtraj/nmr/shift_wrappers.py", line 305, in chemical_shifts_spartaplus
    results = results.pivot_table(rows=["resSeq", "name"], cols="frame", values="SHIFT")
TypeError: pivot_table() got an unexpected keyword argument 'rows'
----------------------------------------------------------------------
Ran 1111 tests in 304.777s
```

**Comment by rmcgibbo** [comment]
(I guess that is #798)

**Comment by kyleabeauchamp** [comment]
sigh, time for me to pay the piper

**Comment by rmcgibbo** [comment]
what about https://github.com/rmcgibbo/mdtraj/commit/7921b5944dc34d16bca06822bcd140d0db9b6ac5

**Comment by kyleabeauchamp** [comment]
IMHO that looks right according to my reading of the docs:

```
http://pandas.pydata.org/pandas-docs/version/0.13.1/generated/pandas.tools.pivot.pivot_table.html?highlight=pivot#pandas.tools.pivot.pivot_table

http://pandas.pydata.org/pandas-docs/version/0.14.0/generated/pandas.tools.pivot.pivot_table.html?highlight=pivot#pandas.tools.pivot.pivot_table
```

**Comment by kyleabeauchamp** [comment]
+1 if travis passes

**Comment by rmcgibbo** [comment]
Also needed to be changed in one other place in the same file. Tested locally (py34, pandas 0.16) and it passes there.

**Pull request merged**
