### PR TITLE
Fix geometry compilation for Windows

### LINKED ISSUE #1092: Compilation failure on windows
```
mdtraj/geometry/src/sasa.cpp(156) : error C2668: 'sqrt' : ambiguous call to overloaded function 
        c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(589): could be 'long double sqrt(long double)'
        c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(541): or       'float sqrt(float)'
        c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\INCLUDE\math.h(127): or       'double sqrt(double)'
        while trying to match the argument list '(int)'

```

### PR DESCRIPTION
**Pull request by mpharrigan**
Supersedes #1100 
cc #1077 
fixes #1092 

I removed the "static" option because it was giving me compilation errors. something about dll's. Now it still gives a warning `mdtraj/geometry/src/geometry.cpp(31): warning C4273: 'roundf': inconsistent dll linkage`

### CODE REVIEW

**Comment by mpharrigan** [comment]
New test failures now that the tests are running (local, numpy 1.10, py3.5)
```
======================================================================
ERROR: mdtraj.tests.test_reporter.test_reporter
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mph\Miniconda3\envs\_test\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Users\mph\Miniconda3\envs\_test\lib\site-packages\numpy\testing\decorators.py", line 146, in skipper_func
    return f(*args, **kwargs)
  File "C:\Users\mph\Miniconda3\envs\_test\lib\site-packages\mdtraj\tests\test_reporter.py", line 107, in test_reporter
    dcd_traj = md.load(dcdfile, top=get_fn('native.pdb'))
  File "C:\Users\mph\Miniconda3\envs\_test\lib\site-packages\mdtraj\core\trajectory.py", line 421, in load
    value = loader(filename, **kwargs)
  File "mdtraj\formats\dcd\dcd.pyx", line 136, in dcd.load_dcd (mdtraj/formats/dcd/dcd.c:1922)
  File "mdtraj\formats\dcd\dcd.pyx", line 223, in dcd.DCDTrajectoryFile.__cinit__ (mdtraj/formats/dcd/dcd.c:2430)
OSError: Could not open file: C:\Users\mph\AppData\Local\Temp\tmpfo_a9qgt\test1\traj.dcd

======================================================================
ERROR: mdtraj.tests.test_reporter.test_reporter_subset
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mph\Miniconda3\envs\_test\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Users\mph\Miniconda3\envs\_test\lib\site-packages\numpy\testing\decorators.py", line 146, in skipper_func
    return f(*args, **kwargs)
  File "C:\Users\mph\Miniconda3\envs\_test\lib\site-packages\mdtraj\tests\test_reporter.py", line 184, in test_reporter_subset
    dcd_traj = md.load(dcdfile, top=hdf5_traj)
  File "C:\Users\mph\Miniconda3\envs\_test\lib\site-packages\mdtraj\core\trajectory.py", line 421, in load
    value = loader(filename, **kwargs)
  File "mdtraj\formats\dcd\dcd.pyx", line 136, in dcd.load_dcd (mdtraj/formats/dcd/dcd.c:1922)
  File "mdtraj\formats\dcd\dcd.pyx", line 223, in dcd.DCDTrajectoryFile.__cinit__ (mdtraj/formats/dcd/dcd.c:2430)
OSError: Could not open file: C:\Users\mph\AppData\Local\Temp\tmpfo_a9qgt\test_2\traj.dcd

======================================================================
FAIL: mdtraj.geometry.tests.test_sasa.test_sasa_1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\mph\Miniconda3\envs\_test\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\Users\mph\Miniconda3\envs\_test\lib\site-packages\mdtraj\geometry\tests\test_sasa.py", line 86, in test_sasa_1
    assert_approx_equal(areas[0], true)
  File "C:\Users\mph\Miniconda3\envs\_test\lib\site-packages\numpy\testing\utils.py", line 611, in assert_approx_equal
    raise AssertionError(msg)
AssertionError:
Items are not equal to 7 significant digits:
 ACTUAL: 0.4075745642185211
 DESIRED: 0.40715040790523727
```

**Comment by mpharrigan** [comment]
Added a check so it only defines roundf for old visual studio, which prevents compiler warning on vs2015

**Comment by mpharrigan** [comment]
Partially reverts #1090

**Comment by mpharrigan** [comment]
I don't have vs2008 installed on my laptop (takes up too much disk space). Can we drop support for python 2.7 on windows?

**Comment by mpharrigan** [comment]
Actually I have a lead

@rmcgibbo what is the "cephes" implementation of isnan and cbrt. Can we drop it? It only seems to be used in drid

**Comment by rmcgibbo** [comment]
It's an implementation of those functions from a standard math library, since they were missing on vs2008. Could link there, or it might be easier and sufficient to strip it out and just use `x!=x` and raise things to the 1/3 power.

**Comment by mpharrigan** [comment]
Hmm, well it *was* supposed to be linked. `cephes.c` was included as a "source" for the drid extension. Maybe it's a c vs c++ symbol thing?

**Comment by mpharrigan** [comment]
Greens all around!

**Comment by rmcgibbo** [comment]
Nice!

**Pull request merged**
