### PR TITLE
Update devtools readme

### PR DESCRIPTION
**Pull request by mpharrigan**

### CODE REVIEW

**Comment by rmcgibbo** [comment]
Is this why the PyPI package is 17.6MB?

**Comment by mpharrigan** [comment]
??

I don't know why pypi is big

**Comment by rmcgibbo** [comment]
When I looked at the diff, I saw that you moved "make sure to run `git clean -fdx`" to be more prominent, so I had guessed that the bug in the release that you referred to in the other issue might have been that. But I guess not.

**Comment by mpharrigan** [comment]
No, that was always there and bold. I made fewer words bold :)

`3pqr_memb.psf` is 28 mb

**Comment by mpharrigan** [comment]
```
$ du -hd2 | sort -h
28K     ./mdtraj/nmr
32K     ./mdtraj/reporters
36K     ./mdtraj/scripts
44K     ./mdtraj.egg-info
88K     ./examples
164K    ./mdtraj/core
168K    ./mdtraj/html
212K    ./mdtraj/rmsd
264K    ./mdtraj/tests
420K    ./mdtraj/geometry
452K    ./mdtraj/utils
1.1M    ./mdtraj/formats
58M     ./mdtraj/testing
61M     .
61M     ./mdtraj
```

**Comment by rmcgibbo** [comment]
Mmmm. We should try to fix that. Seems unnecessary.

**Comment by mpharrigan** [comment]
+1

**Comment by mpharrigan** [comment]
cc #982

**Pull request merged**
