### PR TITLE
Fixed a compilation error

### PR DESCRIPTION
**Pull request by peastman**

### CODE REVIEW

**Comment by mpharrigan** [comment]
@peastman : did you see #1101 ?

1. Can you go over the changes and make sure I didn't do anything dumb
2. I suspect this PR will break python 2.7 on windows, which doesn't have std::nan (?)

**Comment by peastman** [comment]
`std::isnan()` is completely standard.  It's found in `cmath`:

http://en.cppreference.com/w/cpp/numeric/math/isnan

So Windows shouldn't have any problem with it, and it doesn't matter what Python version you're using.

**Comment by mpharrigan** [comment]
Are you sure it works with visual studio 2008? The python version dictates the visual studio version

**Comment by peastman** [comment]
Do you have reason to think it doesn't work?

If in doubt, `isnan(x)` can be replaced with `x != x`.

**Comment by mpharrigan** [comment]
Yes. It wasn't compiling on appveyor. Please see #1100 and #1101 where @rmcgibbo and I implemented the nan check you describe above

Your link above also describes it as a c++11 feature.

Did you observe a compilation failure without this pr (i.e. without the namespace prepended)? It compiles on travis and on my machines (with gcc)

**Comment by peastman** [comment]
If the issue is already being fixed elsewhere, I can close this.

**Comment by mpharrigan** [comment]
Did you actually observe a compilation failure with the `std::`s omitted? Or can this be closed?

**Comment by ctk3b** [comment]
Related to #1097 ?

**Comment by peastman** [comment]
Yes.  When I pulled the latest changes a few days ago, it started failing to compile.  This change made it compile again.  It looks like the same problem as #1097.

**Comment by mpharrigan** [comment]
Is it a clang thing?

**Comment by mpharrigan** [comment]
I suspect we can fix it without breaking the windows bodge by putting `using std::isnan` at the top

**Comment by mpharrigan** [comment]
We should also add travis mac build to the matrix

**Comment by rmcgibbo** [comment]
> We should also add travis mac build to the matrix

Good idea. That should be relatively simple, although some of the external test dependencies like SPARTA+ and stuff might be more problematic.

**Comment by peastman** [comment]
Or just define our own `isnan()` that checks for `x != x`.

**Comment by marscher** [comment]
Am 29.04.2016 um 19:15 schrieb peastman:
> Or just define our own |isnan()| that checks for |x != x|.
x != x can be optimized away by some super clever compilers.

**Comment by peastman** [comment]
Generally those optimizations have to be explicitly enabled.  For example, gcc has a `-ffinite-math-only` flag which tells the compiler it can assume numbers will never be inf or nan.  But that isn't included in any of the `-0#` optimization levels.  It's usually safe to assume math will be IEEE compliant unless you've specifically told the compiler it doesn't have to be.

**Comment by marscher** [comment]
I'm pretty sure gcc and clang obey this. But can we ever be sure about M$ compilers?

**Comment by peastman** [comment]
See https://msdn.microsoft.com/en-us/library/e7s85ffb.aspx.  The default behavior is `/fp:precise`, for which is specifies:

> The compiler correctly handles comparisons that involve NaN. For example, x != x evaluates to true if x is NaN and ordered comparisons involving NaN raise an exception.

**Comment by marscher** [comment]
Ah thanks, didn't know that.

**Comment by mpharrigan** [comment]
It would be really annoying if microsoft didn't provide `isnan` and also optimized away `x != x`

**Pull request closed without merging**
