### PR TITLE
Make 1.10.1 release notes

### PR DESCRIPTION
**Pull request by mattwthompson**
Here's the GitHub-generated Markdown blob:

```
## What's Changed
* Issue 1829 by @CharlieLaughton in https://github.com/mdtraj/mdtraj/pull/1841
* Add atom selection via atom_indices to SASA computation (try #2, three years after) by @gph82 in https://github.com/mdtraj/mdtraj/pull/1844
* [WIP] ReadTheDocs migration by @sukritsingh in https://github.com/mdtraj/mdtraj/pull/1888
* Fix netCDF file loading to no longer import scipy (and add netCDF to CI reqs) by @sukritsingh in https://github.com/mdtraj/mdtraj/pull/1894
* AST-related modifications by @jeremyleung521 in https://github.com/mdtraj/mdtraj/pull/1898
* Allow appending to HDF5 files using `trajectory.save_hdf5` by @sukritsingh in https://github.com/mdtraj/mdtraj/pull/1899
* Mock-testing dependency absence for netCDF4 by @jeremyleung521 in https://github.com/mdtraj/mdtraj/pull/1895
* remove deprecated oldest-supported-numpy by @sroet in https://github.com/mdtraj/mdtraj/pull/1902
* remove remaining instances of six by @jeremyleung521 in https://github.com/mdtraj/mdtraj/pull/1908
* Replace `xdrlib` with `mda_xdrlib` by @chrisjonesBSU in https://github.com/mdtraj/mdtraj/pull/1911
* Add mda-xdrlib to setup.py requirements by @dwhswenson in https://github.com/mdtraj/mdtraj/pull/1913
* Set up versioneer by @mattwthompson in https://github.com/mdtraj/mdtraj/pull/1909
* drop distutils from tests by @dotlambda in https://github.com/mdtraj/mdtraj/pull/1916
* Remove unused Python xdrlib import by @padix-key in https://github.com/mdtraj/mdtraj/pull/1919
* fix pdbstructure "vmd convention" false-positive by @jeremyleung521 in https://github.com/mdtraj/mdtraj/pull/1904
* Fix RMSD externs to be compatible with Cython 3.0. by @Augustin-Zidek in https://github.com/mdtraj/mdtraj/pull/1917

## New Contributors
* @chrisjonesBSU made their first contribution in https://github.com/mdtraj/mdtraj/pull/1911
* @dotlambda made their first contribution in https://github.com/mdtraj/mdtraj/pull/1916
* @Augustin-Zidek made their first contribution in https://github.com/mdtraj/mdtraj/pull/1917

**Full Changelog**: https://github.com/mdtraj/mdtraj/compare/1.10.0...1.10.1

### CODE REVIEW

**Comment by mattwthompson** [comment]
@Lnaden could you glance through these briefly?

**Comment by janash** [comment]
I'm fine with these release notes.

Although, can someone comment on 

```
**Full Changelog**: https://github.com/mdtraj/mdtraj/compare/1.10.0...1.10.1
```

That URL doesn't show me anything (will it be populated after)?

My preference would be to get this release out, particularly because it should fix the bug with NetCDF reported in #1893

**Review by janash — APPROVED** [review]

**Comment by mattwthompson** [comment]
Nice catch - yeah, I think that'll be populated after hitting the green button. The tag is created at the same time as the release and I'm pretty sure that URL is auto-generated

**Comment by mattwthompson** [comment]
For philosophical reasons I don't make releases after midday Thursday, but I'll tag this Monday!

Then, I'll trigger the `conda-forge` bots to do their thing and we can work on getting wheels for common platforms uploaded

**Comment by janash** [comment]
Thanks @mattwthompson ! I completely understand that philosophy! :) 

I tend to somehow get around to things I've missed on Friday afternoons

**Pull request merged**
