### PR TITLE
Remove very annoying warnings filter

### PR DESCRIPTION
**Pull request by rmcgibbo**
Sorry for all the pain I caused you, @mpharrigan.

### CODE REVIEW

**Comment by mpharrigan** [comment]
Oh, I was going to submit a pr that uses the module filter so we can still get mdtraj warnings

**Comment by mpharrigan** [comment]
maybe even that's a little overbearing

**Comment by rmcgibbo** [comment]
I guess that would be fine. I think it seems better perhaps just to not mess with the filters and let the client decide.

**Comment by mpharrigan** [comment]
yeah, let's not mess with it

**Comment by marscher** [comment]
Ah there we got it... Thank you! It caused a lot of trouble with new IPython notebook version deprecation warnings spam. Hope this will be released soon.

**Comment by Carreau** [comment]
Having filter turned on for a specific module is relatively easy. 
IPython does turn the DeprecationWarning only in `__main__` on by default. We are pushing to have that true in Python repl as well. you can help pushing if you like.

http://bugs.python.org/issue24294

I'm working on simpler way to filter warning in CI when using nose:

https://github.com/Carreau/nose_warnings_filters

If it can helps you...

**Pull request merged**
