### PR TITLE
Follow the Amber NetCDF Trajectory Spec (for compatibility with cpptraj)

### PR DESCRIPTION
**Pull request by mpharrigan**
`cpptraj` was refusing to read mdtraj-generated `.nc` files because we weren't following the spec to a T (or an "xyz")

This fixes it and adds a test. The test requires cpptraj. Should we skip on travis and how?

### CODE REVIEW

**Comment by rmcgibbo** [comment]
you can skip on travis by adding a `@skipif` decorator, and testing on the travis environment variable. i'll figure out the best way to get cpptraj on travis.

**Comment by rmcgibbo** [comment]
See e.g. the tests against DSSP https://github.com/mdtraj/mdtraj/blob/master/mdtraj/geometry/tests/test_dssp.py#L55

**Comment by mpharrigan** [comment]
Skipped

**Comment by rmcgibbo** [comment]
something bad is happening on travis related to numpy and compilation.

**Comment by rmcgibbo** [comment]
@mpharrigan might be possible to add cpptraj to the travis config using the amber conda channel: https://github.com/omnia-md/conda-recipes/issues/340#issuecomment-146746320

**Comment by mpharrigan** [comment]
Conda is installing numpy 1.10 regardless of env variable (?)

Could this be conflicting somehow

**Comment by rmcgibbo** [comment]
The  issue is from https://github.com/conda/conda-build/pull/573, and it's because the version of numpy used during compilation isn't being included in the build string anymore.

**Pull request merged**
