### PR TITLE
[formats/dcd] handle stride like numpy

### PR DESCRIPTION
**Pull request by marscher**
This yields almost the same frames a it used to,
but at the end of the trajectory there were some
frames missing in the current impl.
In PyEMMA we rely upon mdtraj is handling the
stride like numpy.

Added hints on howto improve the reader further
(efficient seeking by byte offset)

### CODE REVIEW

**Comment by marscher** [comment]
This now gracefully handles reading errors during seeking. We should really utilize the constant byte offsets within the dcd format for seeking in the future.

**Comment by marscher** [comment]
On 14.05.2018 22:30, Robert T. McGibbon wrote:
> Merged #1352.
> 

sorry this one was not yet ready... There was even a failing test due to
the changes in the dcd reader. I will add a follow up PR soon.

**Comment by rmcgibbo** [comment]
Oh, sorry!

**Comment by rmcgibbo** [comment]
I'm always worried about my tendency to let PRs languish here -- clearly I overcompensated!

**Pull request merged**
