### PR TITLE
Add XTCReporter for OpenMM 

### PR DESCRIPTION
**Pull request by cescgina**
Add an XTCReporter for OpenMM with support for atom subsets and append mode.

### CODE REVIEW

**Comment by marscher** [comment]
Thanks for your contribution - this looks pretty useful. I think the newly provided test will not be executed, because we do not install openmm in the test-environment (maybe we should change that?).

**Comment by marscher** [comment]
openmm is present in most testing environments. So we can rely upon CI here.

**Comment by cescgina** [comment]
Great! I have a question about the tests, in the documentation it says that they should be run using nosetest, however I could not get them to work, but I could run them through pytest, is that how it's supposed to work and the docs are outdated or there is some problem in my installation? I had an error similar to issue #1340.

**Comment by marscher** [comment]
thanks for pointing this out. I created another PR to fix the documentation pointing to pytest.

**Comment by marscher** [comment]
@cescgina can I push to your branch?

**Comment by cescgina** [comment]
Yes, no problem. Should I add you as a collaborator on my fork?

**Comment by marscher** [comment]
you don't need to, just enable "enable edits from maintainers", which should be the default option, afaik.

**Comment by cescgina** [comment]
Ok, found it, the option is active

**Comment by marscher** [comment]
I do not understand why the test skipping does not work. It works locally (with negated condition :grin:) on pytest-4.0.0

**Comment by marscher** [comment]
https://docs.pytest.org/en/latest/skipping.html#id1 it is even the documented semantics...

**Comment by cescgina** [comment]
Thanks @marscher! Now it works perfectly.

**Comment by marscher** [comment]
On 20.11.18 11:18, Joan Francesc Gilabert wrote:
> Thanks @marscher! Now it works perfectly.
> 
You're welcome. However I did not figure out why the test skipping on
windoze does not work (on the other platforms). The used semantics are
exactly the same as in the other testing units.

**Comment by marscher** [comment]
For now I could only spot failures due to the notorious MOL2 thing and the notebook examples. Anybody else want to review this?

**Pull request merged**
