### PR TITLE
Fix py35 deprecation warning

### LINKED ISSUE #987: DeprecationWarning in Py35
I'm seeing some deprecation warnings in py35.

The relevant [piece of code](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/hdf5.py#L90-L91) that's throwing the warning is
```
# hack for to set argpsec for our custon [sic] numpydoc sphinx extension
setattr(wrapper, '__argspec__', inspect.getargspec(f))
```

Maybe that hack's time has passed.

```
$ python -c 'import mdtraj'
/Users/rmcgibbo/miniconda/lib/python3.5/site-packages/mdtraj/formats/hdf5.py:91: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  setattr(wrapper, '__argspec__', inspect.getargspec(f))
/Users/rmcgibbo/miniconda/lib/python3.5/site-packages/mdtraj/formats/hdf5.py:91: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  setattr(wrapper, '__argspec__', inspect.getargspec(f))
/Users/rmcgibbo/miniconda/lib/python3.5/site-packages/mdtraj/formats/hdf5.py:91: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  setattr(wrapper, '__argspec__', inspect.getargspec(f))
/Users/rmcgibbo/miniconda/lib/python3.5/site-packages/mdtraj/formats/hdf5.py:91: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  setattr(wrapper, '__argspec__', inspect.getargspec(f))
/Users/rmcgibbo/miniconda/lib/python3.5/site-packages/mdtraj/formats/hdf5.py:91: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  setattr(wrapper, '__argspec__', inspect.getargspec(f))
/Users/rmcgibbo/miniconda/lib/python3.5/site-packages/mdtraj/formats/hdf5.py:91: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  setattr(wrapper, '__argspec__', inspect.getargspec(f))
/Users/rmcgibbo/miniconda/lib/python3.5/site-packages/mdtraj/formats/hdf5.py:91: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  setattr(wrapper, '__argspec__', inspect.getargspec(f))
/Users/rmcgibbo/miniconda/lib/python3.5/site-packages/mdtraj/formats/hdf5.py:91: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  setattr(wrapper, '__argspec__', inspect.getargspec(f))
/Users/rmcgibbo/miniconda/lib/python3.5/site-packages/mdtraj/formats/hdf5.py:91: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  setattr(wrapper, '__argspec__', inspect.getargspec(f))
/Users/rmcgibbo/miniconda/lib/python3.5/site-packages/mdtraj/formats/hdf5.py:91: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  setattr(wrapper, '__argspec__', inspect.getargspec(f))
/Users/rmcgibbo/miniconda/lib/python3.5/site-packages/mdtraj/formats/hdf5.py:91: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  setattr(wrapper, '__argspec__', inspect.getargspec(f))
/Users/rmcgibbo/miniconda/lib/python3.5/site-packages/mdtraj/formats/hdf5.py:91: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  setattr(wrapper, '__argspec__', inspect.getargspec(f))
/Users/rmcgibbo/miniconda/lib/python3.5/site-packages/mdtraj/formats/hdf5.py:91: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  setattr(wrapper, '__argspec__', inspect.getargspec(f))
/Users/rmcgibbo/miniconda/lib/python3.5/site-packages/mdtraj/formats/hdf5.py:91: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  setattr(wrapper, '__argspec__', inspect.getargspec(f))
/Users/rmcgibbo/miniconda/lib/python3.5/site-packages/mdtraj/formats/hdf5.py:91: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  setattr(wrapper, '__argspec__', inspect.getargspec(f))
/Users/rmcgibbo/miniconda/lib/python3.5/site-packages/mdtraj/formats/hdf5.py:91: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  setattr(wrapper, '__argspec__', inspect.getargspec(f))
/Users/rmcgibbo/miniconda/lib/python3.5/site-packages/mdtraj/formats/hdf5.py:91: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  setattr(wrapper, '__argspec__', inspect.getargspec(f))
/Users/rmcgibbo/miniconda/lib/python3.5/site-packages/mdtraj/formats/hdf5.py:91: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  setattr(wrapper, '__argspec__', inspect.getargspec(f))
/Users/rmcgibbo/miniconda/lib/python3.5/site-packages/scipy/_lib/decorator.py:205: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  first = inspect.getargspec(caller)[0][0]  # first arg
```

### PR DESCRIPTION
**Pull request by rmcgibbo**
Fixes #987. Based on https://github.com/scipy/scipy/pull/5248#issuecomment-146892550, I got the impression that copying in decorator.py was the easiest way to do this.

### CODE REVIEW

**Comment by mpharrigan** [comment]
This seems ... complicated. Does `ensure_mode` need to be a decorator?

**Comment by rmcgibbo** [comment]
Not really. This seemed like the easiest thing, since it's some ancient package that's used in lots of stuff. We could depend on it, but that's more of an issue.

**Comment by rmcgibbo** [comment]
We already have a couple similar things in util.external

**Comment by rmcgibbo** [comment]
Mmm. Maybe never mind. I should have looked at the tests first.

**Comment by rmcgibbo** [comment]
I will take your advice and make it just not b e a decorator.

**Pull request closed without merging**
