### PR TITLE
scipy.stats.nanmean deprecated

### PR DESCRIPTION
**Pull request by smsaladi**
in favor of numpy.nanmean

http://docs.scipy.org/doc/scipy-0.17.0/reference/generated/scipy.stats.nanmean.html

Seems to be API compatible.

### CODE REVIEW

**Comment by rmcgibbo** [comment]
Looks like np.nanmean was added in 1.8.0. Currently I think we support 1.7 and maybe even 1.6. http://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.nanmean.html

**Comment by mpharrigan** [comment]
Can we change numpy required version to 1.8

**Comment by mpharrigan** [comment]
It looks like this function was actually removed in scipy 0.18

**Comment by smsaladi** [comment]
How about this?

**Comment by mpharrigan** [comment]
Oh yeah that looks good

**Pull request merged**
