### PR TITLE
Run macosx tests

### PR DESCRIPTION
**Pull request by mpharrigan**

### CODE REVIEW

**Comment by mpharrigan** [comment]
cc #1104 

The compilation error shows up clear as day. I can't replicate the build error on my linux system when using clang

**Comment by mpharrigan** [comment]
Switching from `<cmath>` to `<math.h>` fixed the compilation error

**Comment by tcmoore3** [comment]
What was wrong with using ```std::isnan```

**Comment by mpharrigan** [comment]
visual studio 2008, needed for python 2.7 for abi compatibility, does not have `std::isnan`. We get around it by defining a macro for `isnan` in that case

**Pull request merged**
