### PR TITLE
Implement reading and writing PDBx/mmCIF files

### LINKED ISSUE #652: [FR] PDBx/mmCIF support
wwPDB [recently announced](http://www.wwpdb.org/news/news_2014.html#18-September-2014) that large structures/complexes (100000+ atoms) will only be available in [PDBx/mmCIF](http://mmcif.wwpdb.org/) formats.

I'm assuming the current PDB loader won't be able to handle these files. Would support for these formats be handy?

### PR DESCRIPTION
**Pull request by peastman**
Fixes #652.  This implementation uses OpenMM to do most of the work.

### CODE REVIEW

**Comment by rmcgibbo** [comment]
It’s surprising to see segfaults in the test log

**Comment by peastman** [comment]
Any idea what's causing it?  The segfault appears to happen in `test_image_molecules`.  Nothing in this PR is related to that.

**Comment by rmcgibbo** [comment]
Absolutely no idea. I’ll try to reproduce locally.

**Comment by rmcgibbo** [comment]
I restarted the CI jobs on the current master branch: https://github.com/mdtraj/mdtraj/actions/runs/1772802025

**Comment by rmcgibbo** [comment]
This is what I see locally:
```
python3.9-mdtraj> =================================== FAILURES ===================================
python3.9-mdtraj> _________________________________ test_convert _________________________________
python3.9-mdtraj> get_fn = <function get_fn.<locals>._get_fn at 0x7fff9bd64940>
python3.9-mdtraj>     def test_convert(get_fn):
python3.9-mdtraj>         for filename in ['2EQQ.pdb', '4OH9.pdb']:
python3.9-mdtraj>             # Load a PDB file.
python3.9-mdtraj>             traj1 = load(get_fn(filename))
python3.9-mdtraj>             with tempfile.NamedTemporaryFile(suffix='.pdbx', mode='w', delete=False) as file:
python3.9-mdtraj>                 # Save it in PDBx/mmCIF format.
python3.9-mdtraj> >               pdbx1 = PDBxTrajectoryFile(file.name, mode='w')
python3.9-mdtraj> tests/test_pdbx.py:37:
python3.9-mdtraj> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
python3.9-mdtraj> self = <mdtraj.formats.pdbx.PDBxTrajectoryFile object at 0x7fff94ebef10>
python3.9-mdtraj> filename = '/build/tmp8xi6imds.pdbx', mode = 'w', force_overwrite = True
python3.9-mdtraj> top = None
python3.9-mdtraj>     def __init__(self, filename, mode='r', force_overwrite=True, top=None):
python3.9-mdtraj>         self._open = False
python3.9-mdtraj>         self._mode = mode
python3.9-mdtraj> >       from openmm.app import PDBxFile
python3.9-mdtraj> E       ModuleNotFoundError: No module named 'openmm'
python3.9-mdtraj> /nix/store/w6pjvfj0yxvw6zw4q88jkssazxy67rkz-python3.9-mdtraj-1.9.8.dev0/lib/python3.9/site-packages/mdtraj/formats/pdbx.py:203: ModuleNotFoundError
```
I think we either need to get openmm into nix (difficult) or make the test only active if openmm is available (easy).

**Comment by mattwthompson** [comment]
The new test passes in my local conda environment (I assume it did in Peter's as well); the easy solution shouldn't produce any surprises. Of course there is other functionality that uses OpenMM so the hard solution would still be useful if anybody ends up pulling it off.

**Comment by rmcgibbo** [comment]
> I'll add a mark to tell pytest to skip it if OpenMM isn't installed. It would be really good if we could get it to install it though. I'm not familiar with nix. What is the difficulty in installing OpenMM during CI?

I think someone would have to add OpenMM to the [nixpkgs](https://nixos.wiki/wiki/Nixpkgs) repository.

> I notice your other classes that use OpenMM still use the simtk prefix from 7.5 and earlier. Are you still maintaining compatibility with old OpenMM versions? If so, I can switch the imports in this code. (This is exactly the sort of thing it would be really useful to have CI testing.)

I think there are two open tickets already about this. If you review them and approve, I'll just merge them?

> None of this explains the segfault though.

True, but my hope is that for some dark magic reason, if you skip this test, everything will work in CI. I'm not confident of that, but it's worth a try.

**Comment by peastman** [comment]
The mark is added.  Good luck with the dark magic.

**Comment by peastman** [comment]
For whatever reason, it worked this time.

**Comment by rmcgibbo** [comment]
Dark magic indeed. I think somehow the failure was being reported incorrectly.

**Comment by rmcgibbo** [comment]
Thanks for adding this, Peter.

**Comment by apayne97** [comment]
Yay! Thank you Peter!

**Pull request merged**
