### PR TITLE
Fix parsing errors for pdb and psf files with nonsequential atoms

### PR DESCRIPTION
**Pull request by Eigenstate**
This should fix issue #1129 , and similar issues parsing psf files.

The origins of the out of order residues is actually from Maestro's add hydrogens, which puts them at the end of the mae file. Converting tends to be done in atom order, so these hydrogens stay at the end of the psf file and away from the rest of the residue.

The parsing functions for pdb and psf were defining a new residue every time they encountered a change in resid. Now, they check if the resid of the current atom has already been defined, and if so add atoms to that residue. Otherwise it behaves as normal and creates a new residue.

I tested this on my out of order pdb and psf files from Anton trajectories.

### CODE REVIEW

**Comment by cxhernandez** [comment]
@mdtraj/developers: should we add the topology from #1129 as a test file and create a test for this bug?

**Comment by peastman** [comment]
We need to be a bit careful about this.  There are so many nonstandard PDB files out there, and they can be nonstandard in so many ways, it's really easy to break the reading of some files when you try to fix others.

PDB files only have four columns for the residue ID, which means a standard PDB file can only have up to 9999 residues.  For more residues, you're officially supposed to split it into multiple files, but hardly anyone does that.  Instead they use various tricks (intentionally or accidentally) to allow more.  Some that I've seen include:

- Writing the residue ID mod 10000.
- Spilling over into the next column (which is supposed to be for the insertion code).
- Just writing **** as the residue ID.

This PR will fail if it gets a file that does any of those, because it will encounter a new residue that has the same value in the residue ID field as a previous one.

**Comment by cxhernandez** [comment]
> This PR will fail if it gets a file that does any of those because it will encounter a new residue that has the same value in the residue ID field as a previous one.

Do we want to encourage non-standard PDBs like that in cases where they should clearly be using PDBx/mmCIF or something more modern? Also, do we want to sacrifice an increasing number of Desmond/Maestro users because people are using the incorrect format to store their topologies?

cc @mpharrigan @kmckiern, who actually work on large systems, for their input

**Comment by peastman** [comment]
Files of this sort are _really_ common.  To put it into perspective, consider that any PDB file with more than 9999 residues or 99,999 atoms is _by definition_ nonstandard.  It has to do something to work around the limited number of columns, and chances are high that "something" will cause this PR to behave incorrectly.  That includes, among other things, files written by mdtraj itself!  It writes the residue ID mod 10,000:

https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/pdb/pdbfile.py#L349

**Comment by mpharrigan** [comment]
Yeah I think it's more common to have > 10000 residues than using a maestro pdb

**Comment by Eigenstate** [comment]
That makes sense. How about just taking the fix for parsing psf files and then having Maestro/Desmond users provide a psf?

**Comment by mpharrigan** [comment]
That sounds good to me. Maybe we could add a flag for pdb parsing

**Pull request closed without merging**
