### PR TITLE
Enhance PSF file topology creation

### PR DESCRIPTION
**Pull request by swails**
This addresses #711.  Also fixes a few typos and docstring mistakes.

Tests have been added.

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
looks ok to me

**Comment by swails** [comment]
Travis is dying with:

```
Could not connect to http://conda.binstar.org/rmcgibbo/linux-64/shiftx2-1.0.7-2.tar.bz2
Error: Connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581): http://conda.binstar.org/rmcgibbo/linux-64/shiftx2-1.0.7-2.tar.bz2
```

appveyor should hopefully work, but I'm not sure what's going on with the SSL certificate for shiftx2.

**Comment by kyleabeauchamp** [comment]
Possibly (?) related to this issue: 
https://github.com/omnia-md/conda-recipes/issues/122

**Comment by synapticarbors** [comment]
I think this is a general problem that people are starting to report:

https://groups.google.com/a/continuum.io/forum/#!topic/conda/IAr9xTwOeC8

**Comment by swails** [comment]
Looks like a likely suspect.  FWIW, the PSF file tests passed on my machine.

**Comment by rmcgibbo** [comment]
I restarted the travis build.

**Comment by rmcgibbo** [comment]
Passed on travis, after fix to request's SSL issues. Merging.

**Pull request merged**
