### PR TITLE
remove simtk support

### LINKED ISSUE #1695: Remove use of `simtk` imports
[OpenMM 7.6.0 removed the top-level `simtk` namespace](https://github.com/openmm/openmm/releases/tag/7.6.0). There is a shim in place for now, but use of `simtk` in imports is now deprecated.

### PR DESCRIPTION
**Pull request by sroet**
closes #1695 

# This drops support for OpenMM < 7.6 

This (together with #1696 ) deals with all the files that came up with 
```grep -r -n "simtk" --include="*.py"```

It completely removes most references to `simtk`, the only ones left are of the type:
```
Medical Research, grant U54 GM072970. See https://simtk.org.
```

last commit [f27472d] is merging  #1696 into this to make tests pass, so merging this will also merge that branch.

### CODE REVIEW

**Comment by mattwthompson** [comment]
My unsolicited opinion here is that, since we just made a release that's backwards-compatble with the `simtk` namespace, we just only support the `openmm` namespace moving forward. It makes things much simpler; if for some reason somebody wants to use something that requires an early 2021 release of OpenMM, they have a late 2021 release of MDTraj that should be a sufficient snapshot in time. (This would require packages in the next release to be pinned to `openmm >=7.6`.)

**Comment by sroet** [comment]
that is fine by me as well. I would like some other stakeholders to give feedback on that as well. Do you mind making an issue and tagging all relevant people?

**Comment by mattwthompson** [comment]
Not sure who would really get in the way; AFAIR OpenMM developers are not supporting backports long-term, and most users (including the use cases I know of within OpenFF) are either moving away from `simtk` altogether or should be fine pinning to v1.9.7 or a slightly older version.

**Comment by sroet** [comment]
Sure, I will implement it. The individual commits should be easy enough to revert if required. I do think that this should be communicated somehow, as `openmm` is not a requirement of `mdtraj`. I don't think we can pin it in a way so it auto-resolves properly in `pip` (there used to be a [constraints.txt](https://pip.pypa.io/en/stable/user_guide/#constraints-files), but that did not seem to be ported to the pyproject.toml standard.), I did [find a way to do it on conda-forge](https://conda-forge.org/docs/maintainer/adding_pkgs.html#constraining-packages-at-runtime).

**Comment by sroet** [comment]
@mattwthompson This should be ready, as stated in the edit of the top comment, f27472d is the merging of #1696 into this branch. This was required for the tests to pass. So merging this will also merge that branch. As stated in that PR it is mostly (except for the utils/unit/__init__.py) a port from the current state of openmm.unit

**Comment by mattwthompson** [comment]
The diff looks fine on a skim, though I'm not going to dig too deeply into it. I assume that `grep -r "simtk" mdtraj/` doesn't produce anything/much?

I notice in the test logs that some OpenMM-dependent tests are skipped:

```
2021-11-16T17:42:59.9983626Z =========================== short test summary info ============================
2021-11-16T17:42:59.9984139Z SKIPPED [2] tests/test_dihedral.py:30: pymol executable not found
2021-11-16T17:42:59.9984963Z SKIPPED [16] tests/test_docstrings.py:31: Skip checking certain modules' docstrings
2021-11-16T17:42:59.9985807Z SKIPPED [1] tests/test_dssp.py:44: This test requires mkdssp to be installed, from http://swift.cmbi.ru.nl/gv/dssp/
2021-11-16T17:42:59.9986753Z SKIPPED [1] tests/test_dssp.py:52: This test requires mkdssp to be installed, from http://swift.cmbi.ru.nl/gv/dssp/
2021-11-16T17:42:59.9987707Z SKIPPED [1] tests/test_dssp.py:59: This test requires mkdssp to be installed, from http://swift.cmbi.ru.nl/gv/dssp/
2021-11-16T17:42:59.9988492Z SKIPPED [1] tests/test_geometry.py:243: Not doing performance testing
2021-11-16T17:42:59.9989108Z SKIPPED [1] tests/test_geometry.py:261: Not doing performance testing
2021-11-16T17:42:59.9989906Z SKIPPED [1] tests/test_hbonds.py:43: This test requires mkdssp to be installed, from http://swift.cmbi.ru.nl/gv/dssp/
2021-11-16T17:42:59.9990650Z SKIPPED [1] tests/test_hdf5.py:99: requires openmm.units
2021-11-16T17:42:59.9991313Z SKIPPED [1] tests/test_hdf5.py:133: requires openmm.units
2021-11-16T17:42:59.9991884Z SKIPPED [1] tests/test_hdf5.py:186: requires openmm.units
2021-11-16T17:42:59.9992388Z SKIPPED [1] tests/test_mol2.py:55: Requires obabel
2021-11-16T17:42:59.9993124Z SKIPPED [1] tests/test_netcdf.py:248: This test requires cpptraj from AmberTools to be installed (http://ambermd.org)
2021-11-16T17:42:59.9993840Z SKIPPED [1] tests/test_nmr.py:11: SPARTA+ binary not found
2021-11-16T17:42:59.9994346Z SKIPPED [1] tests/test_nmr.py:24: PPM binary not found
2021-11-16T17:42:59.9994961Z SKIPPED [1] tests/test_nmr.py:38: SHIFTX2 binary not found or Python 2 not found or runningn on travis.
2021-11-16T17:42:59.9995777Z SKIPPED [2] tests/test_psf.py:92: This test requires the VMD executable: http://www.ks.uiuc.edu/Research/vmd/
2021-11-16T17:42:59.9996575Z SKIPPED [1] tests/test_rdf.py:66: Binning does not match up with gromacs currently.
2021-11-16T17:42:59.9997214Z SKIPPED [1] tests/test_rdf.py:153: Binning does not match up with gromacs currently.
2021-11-16T17:42:59.9997872Z SKIPPED [1] tests/test_reporter.py:47: test_reporter.py needs OpenMM.
2021-11-16T17:42:59.9998531Z SKIPPED [1] tests/test_reporter.py:121: test_reporter.py needs OpenMM.
2021-11-16T17:42:59.9999170Z SKIPPED [1] tests/test_reporter.py:201: test_reporter.py needs OpenMM.
```

Probably a decorator of some sort isn't processing an import

**Comment by sroet** [comment]
> Probably a decorator of some sort isn't processing an import

openmm isn't installed in the CI, [as the same skip happens on master](https://github.com/mdtraj/mdtraj/runs/4194793045?check_suite_focus=true#step:5:3043)

>  I assume that grep -r "simtk" mdtraj/ doesn't produce anything/much?


```
(base) sroet@XPS-15-9570:~/github_files/mdtraj$ grep -r "simtk" mdtraj/ --exclude-dir="__pycache__*"
mdtraj/geometry/include/vectorize_sse.h: * Medical Research, grant U54 GM072970. See https://simtk.org.               *
mdtraj/geometry/include/vectorize_neon.h: * Medical Research, grant U54 GM072970. See https://simtk.org.               *
mdtraj/geometry/include/vectorize.h: * Medical Research, grant U54 GM072970. See https://simtk.org.               *
mdtraj/core/element.py:Medical Research, grant U54 GM072970. See https://simtk.org.
mdtraj/formats/pdb/README.md:- Removed all of the units, so that this can operate without simtk.units
mdtraj/utils/unit/baseunit.py:Medical Research, grant U54 GM072970. See https://simtk.org.
mdtraj/utils/unit/unit_operators.py:Medical Research, grant U54 GM072970. See https://simtk.org.
mdtraj/utils/unit/prefix.py:Medical Research, grant U54 GM072970. See https://simtk.org.
mdtraj/utils/unit/standard_dimensions.py:Medical Research, grant U54 GM072970. See https://simtk.org.
mdtraj/utils/unit/quantity.py:Medical Research, grant U54 GM072970. See https://simtk.org.
mdtraj/utils/unit/unit_math.py:Medical Research, grant U54 GM072970. See https://simtk.org.
mdtraj/utils/unit/constants.py:Medical Research, grant U54 GM072970. See https://simtk.org.
mdtraj/utils/unit/mymatrix.py:Medical Research, grant U54 GM072970. See https://simtk.org.
mdtraj/utils/unit/unit.py:Medical Research, grant U54 GM072970. See https://simtk.org.
mdtraj/utils/unit/basedimension.py:Medical Research, grant U54 GM072970. See https://simtk.org.
mdtraj/utils/unit/unit_definitions.py:Medical Research, grant U54 GM072970. See https://simtk.org.
```

**Comment by mattwthompson** [comment]
Ahh ... that does make sense. I doubt OpenMM is built in Nix world.

**Review by mattwthompson — APPROVED** [review]

**Comment by peastman** [comment]
I think this is ready to merge.

**Pull request merged**
