### PR TITLE
WIP: Store PDB chain identifier

### PR DESCRIPTION
**Pull request by rmcgibbo**
For #873. There is still an issue to work out with in the test though.

[Review on Reviewable](https://reviewable.io/reviews/mdtraj/mdtraj/876)

### CODE REVIEW

**Comment by mpharrigan** [comment]
Is this worth finishing?

**Comment by evanfeinberg** [comment]
@mpharrigan I think it's worth finishing. Is it safe for me to merge this WIP to use in the mean time while the checks are fixed? Can I help get this working somehow? I think this feature would be particularly useful for simulations that entail protein protein interactions.

**Comment by cxhernandez** [comment]
Fork [this branch](https://github.com/rmcgibbo/mdtraj/tree/wip-chain-ids) and have a crack at it!

``` bash
$ git clone git@github.com:rmcgibbo/mdtraj.git && cd mdtraj
$ git checkout wip-chain-ids
```

**Comment by evanfeinberg** [comment]
Awesome, thanks @cxhernandez

**Comment by evanfeinberg** [comment]
Update on this. Thanks again to @cxhernandez , @rmcgibbo , and @mpharrigan  for working on this. So this WIP PR works like a charm when one reads in a .dcd traj / .pdb top combination into an mdtraj trajectory object. The chains are correctly read in topology.chain.id. However, there is a bug, which I suspect is relatively easy to fix. When saving that mdtraj trajectory object in .h5 format, and then subsequently loading that .h5 file as a new trajectory object, the chain names get messed up. For some reason, they get renamed alphabetically from A to Z. So they topology.chain.id attribute is retained but its  value is reset. I assume this is an issue with either saving or loading or both. 

Can someone suggest how @amirbarati and I might fix this? Any hints would be appreciated.

**Comment by rmcgibbo** [comment]
I suspect you need to modify this method: https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/hdf5.py#L305

**Comment by evanfeinberg** [comment]
Thanks @rmcgibbo , we will have a crack at it this week. Shouldn't be too bad.

**Comment by rmcgibbo** [comment]
@evanfeinberg any progress?

**Comment by evanfeinberg** [comment]
Thanks for  the tips, I think it's fixed. n00b question: how do I commit/push to this particular PR?

**Comment by rmcgibbo** [comment]
Actually, you can't. You want to submit a new PR, but it can incorporate the commits from this PR.

**Comment by rmcgibbo** [comment]
If you're not sure how to do this I can also show you on gchat.

**Comment by mpharrigan** [comment]
Any updates on this @evanfeinberg ?

**Comment by evanfeinberg** [comment]
It's working now but failing in cases where one is loading a trajectory
that lacks chain information to start with. Once that fix is in it should
be done.

**Comment by evanfeinberg** [comment]
Ok I think it's fixed. Will make PR ASAP

**Comment by rmcgibbo** [comment]
This is outdated. Feel free to re-open if desired.

**Pull request closed without merging**
