### PR TITLE
set comprehension

### PR DESCRIPTION
**Pull request by cxhernandez**

### CODE REVIEW

**Comment by mpharrigan** [comment]
Note that this doesn't work in py2.6

**Comment by rmcgibbo** [comment]
Good riddance.

**Comment by mpharrigan** [comment]
:)

**Comment by hainm** [comment]
not sure if it's worth supporting py2.6.

**Comment by rmcgibbo** [comment]
http://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html

**Pull request merged**
