### PR TITLE
adopted to pep518 dependency handling

### LINKED ISSUE #1433: Command "python setup.py egg_info" failed with error code 1
I'm currently attempting to install mdtraj via `requirements.txt`. I've tried collecting mdtraj from pip install mdtraj as well as pip install -e git+git://github.com/mdtraj/mdtraj as shown below. The same error message is given regardless of the method. Both cython >=0.19.0 and numpy >=1.6.0 are installed prior to mdtraj. 

```
/home/docs/checkouts/readthedocs.org/user_builds/biceps/envs/latest/bin/python -m pip install --exists-action=w --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/biceps/.cache/pip -r doc/requirements.txt
Collecting cython>=0.19.0 (from -r doc/requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/d1/05/34111590348c227d8e9f738c4b1ea2dce0410de5a658998f59df629ce57f/Cython-0.29.5-cp27-cp27mu-manylinux1_x86_64.whl (2.0MB)
Requirement already satisfied: numpy>=1.6.0 in /home/docs/.pyenv/versions/2.7.14/lib/python2.7/site-packages (from -r doc/requirements.txt (line 2)) (1.16.0)
Collecting mdtraj==1.9.1 (from -r doc/requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/af/93/8ad08f58668db6e3bf85e402c9c753fa4425c249de276b55f20c08e3fff7/mdtraj-1.9.1.tar.gz (2.0MB)
    Complete output from command python setup.py egg_info:
    --------------------------------------------------------------------------------
    Error: building mdtraj requires numpy and cython>=0.19
    
    Try running the command ``pip install numpy cython`` or
    ``conda install numpy cython``.
    
    or see http://docs.scipy.org/doc/numpy/user/install.html and
    http://cython.org/ for more information.
    
    If you're feeling lost, we recommend downloading the (free) Anaconda python
    distribution https://www.continuum.io/downloads, because it comes with
    these components included.
    --------------------------------------------------------------------------------
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-zxgpqe/mdtraj/
```

```
...
Collecting cython==0.28 (from -r requirements/pip.txt (line 96))
  Using cached https://files.pythonhosted.org/packages/fa/86/0c8311bcba3b3f0944c135db95312e057a353058f522692e4dcf6d4bb978/Cython-0.28.tar.gz
Collecting numpy==1.14 (from -r requirements/pip.txt (line 97))
  Using cached https://files.pythonhosted.org/packages/ee/66/7c2690141c520db08b6a6f852fa768f421b0b50683b7bbcd88ef51f33170/numpy-1.14.0.zip
Obtaining mdtraj from git+git://github.com/mdtraj/mdtraj#egg=mdtraj (from -r requirements/pip.txt (line 98))
  Cloning git://github.com/mdtraj/mdtraj to ./venv/src/mdtraj
    Complete output from command python setup.py egg_info:
    --------------------------------------------------------------------------------
    Error: building mdtraj requires numpy and cython>=0.19

    Try running the command ``pip install numpy cython`` or
    ``conda install numpy cython``.

    or see http://docs.scipy.org/doc/numpy/user/install.html and
    http://cython.org/ for more information.

    If you're feeling lost, we recommend downloading the (free) Anaconda python
    distribution https://www.continuum.io/downloads, because it comes with
    these components included.
    --------------------------------------------------------------------------------

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /Users/.../github/readthedocs.org/venv/src/mdtraj/
```

### PR DESCRIPTION
**Pull request by marscher**
fixes #1433

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
image
 

woo!

**Comment by marscher** [comment]
one definitely needs wheel in this list

**Comment by marscher** [comment]
xref #1441

**Comment by rmcgibbo** [comment]
@marscher: should I merge this PR or #1441?

**Comment by marscher** [comment]
> @marscher <https://github.com/marscher>: should I merge this PR or #1441 
> <https://github.com/mdtraj/mdtraj/pull/1441>?

I have tested this locally. With these changes I can drag in mdtraj as a 
build dependency during a pip source install of PyEMMA. I haven't tested 
1441, so I would recommend using this one.

But I would prefer to add some error handling in case people do not use 
pip and invoke the setup directly [which is a corner case IMO, should I 
postpone it?]

**Comment by salotz** [comment]
> I have tested this locally. With these changes I can drag in mdtraj as a build dependency during a pip source install of PyEMMA.

In my [project](https://github.com/ADicksonLab/wepy/tree/release-features) this isn't working I still get this error when I install with `pip install -e .[mdtraj]`:

```
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: --------------------------------------------------------------------------------
    Error: building mdtraj requires numpy and cython>=0.19
    
    Try running the command ``pip install numpy cython`` or
    ``conda install numpy cython``.
    
    or see http://docs.scipy.org/doc/numpy/user/install.html and
    http://cython.org/ for more information.
    
    If you're feeling lost, we recommend downloading the (free) Anaconda python
    distribution https://www.continuum.io/downloads, because it comes with
    these components included.
    --------------------------------------------------------------------------------
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /home/salotz/tmp/pip-install-e5kiygfv/mdtraj/
```
I'm guessing it works for PYEMMA because it has special cython handling code in the setup to do this lazily. This was the issue with removing that special check and error message on #1441.

**Comment by rmcgibbo** [comment]
martin removed that error message text from the master branch, so i think if you're getting that error message it means you're not pulling in the master branch.

**Comment by salotz** [comment]
I see, I was mistakenly thinking pip install would look at my requirements.txt file

**Comment by marscher** [comment]
> ERROR: Command "python setup.py egg_info" failed with error code 1 in /home/salotz/tmp/pip-install-e5kiygfv/mdtraj/
> ```
> I'm guessing it works for PYEMMA because it has special cython handling code in the setup to do this lazily. This was the issue with removing that special check and error message on #1441.
> 
> 

@salotz In the meantime you can drag in mdtraj via pyproject.toml from 
git like this:

```
  requires = [
   "setuptools",
   "wheel",
   "git+https://github.com/marscher/mdtraj.git@master",
   "pybind11",
   ]

```

I would also recommend using pip >=19, since 18 invokes egg_info prior 
installing the things listed in "requires", which can raise errors.

**Pull request merged**
