### PR TITLE
Fix a test failure in test_reporters.py caused by merge of #1431

### PR DESCRIPTION
**Pull request by rmcgibbo**
cc @jchodera, #1431.

### CODE REVIEW

**Comment by jchodera** [comment]
Thanks for catching this! 

If I understand correctly, the test needed to be fixed because the default behavior has now changed, and unit cells are no longer dropped in some cases.

Sorry about that---I had totally missed the travis test failure in #1431, though it looked like travis caught that failure in that PR:
https://travis-ci.org/mdtraj/mdtraj/jobs/491367893#L3731

**Comment by rmcgibbo** [comment]
In this test, the OpenMM simulation is created with CutoffNonPeriodic. What _values_ end up in the cell_lengths / cell_angles, and are they actually meaningful?

**Comment by jchodera** [comment]
The default periodic box values when creating a `System` would be stored, and no they aren't meaningful. 

Perhaps we should have two tests? One that uses a periodic system and one that uses a non-periodic system?

**Comment by rmcgibbo** [comment]
Got it. This makes sense then.

**Comment by rmcgibbo** [comment]
Yeah, more tests = usually good.

**Pull request merged**
