### PR TITLE
[WIP] OpenMM does not yet support segment_id

### PR DESCRIPTION
**Pull request by jchodera**
Attempting to address #1047.

Will add tests in a moment.

### CODE REVIEW

**Comment by jchodera** [comment]
It looks like there *is* a test for `Topology.from__openmm()`, but it may not have been run because the [nosetests don't install the `openmm` package](https://github.com/mdtraj/mdtraj/blob/master/devtools/conda-recipe/meta.yaml#L25-L34).

Is it OK if I add `openmm` in `test: requires:`?

**Comment by jchodera** [comment]
Hm, appveyor seems to be broken:
```
error: command 'C:\\Users\\appveyor\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\cl.exe' failed with exit status 2 
```

**Comment by jchodera** [comment]
I've added `openmm` to the nosetests so this doesn't break again.

**Comment by jchodera** [comment]
There is some code in `MDTraj` that is apparently supposed to work on either MDTraj or OpenMM `Topology` objects even though they are fundamentally incompatible. I think this is a deeper issue, but I am applying a band-aid for now.

The HDF5 failure is more serious.  There is a cast of `residue.resSeq`---which is a *string* for OpenMM---to an `int`, which is fundamentally not allowed. I don't know how to fix that without rearchitecting your HDF5 data model.

**Comment by mpharrigan** [comment]
Thanks @jchodera 

Looks like the addition of openmm uncovered some new test failures. Upon first glance it looks like the reporter objects are using openmm topology and assuming it's the same as an mdtraj topology

**Comment by mpharrigan** [comment]
Subsumes #1048

**Comment by jchodera** [comment]
Well, there's code in there that really states that is a fundamental assumption:
```
Note
    ----
    This really should be a copy constructor (class method) on Topology,
    but I want it to work on either the mdtraj topology OR the OpenMM
    topology. An inplace version for the topology object we have here
    is also available.
```

**Comment by mpharrigan** [comment]
Could you point me to that note? Can it use the from_openmm method you just fixed?

**Comment by jchodera** [comment]
I still think you should rip out https://github.com/mdtraj/mdtraj/commit/c4d43469705f395e21d2a6dc789223f4e0bbc6d3 wholesale.  It wasn't a mostly-working PR with a bug or two. It fundamentally violates deep assumptions made within MDTraj.

**Comment by jchodera** [comment]
Here you go!

https://github.com/mdtraj/mdtraj/blob/master/mdtraj/core/topology.py#L69-L94

If you figure out there are more minor changes that would actually make things work, let me know---I'm happy to make them.

**Pull request closed without merging**
