### PR TITLE
Pin astun parse for python==3.8

### PR DESCRIPTION
**Pull request by sroet**
The CI on master was suspiciously passing for python`3.8` before issue #1613 was reported. Looking at the differences it seems like astunparse=`1.6.2` passes for python `3.8` and `3.9`. This pins that requirement for these python versions (and is build on top of #1619)

### CODE REVIEW

**Comment by sroet** [comment]
Wait before merging this as from [this comment](https://github.com/simonpercivall/astunparse/issues/43#issuecomment-743255764) it seems like `astunparse` should be compatible with python 39. Testing it now

**Comment by sroet** [comment]
Alright, this solves `pip installing` but as seen from the CI this is not taken into account when building the conda environment in the CI. @rmcgibbo do you know where this environment recipe is pulled from? Is it conda-forge/mdtraj-feedstock or some place else?

**Comment by rmcgibbo** [comment]
Right -- I think you found it. That's the recipe that used for conda on the CI and then for the releases it's https://github.com/conda-forge/mdtraj-feedstock/blob/master/recipe/meta.yaml.

**Comment by sroet** [comment]
So all python version have 1 error left, which is due to a missing Sparta+ for the notebook check.

It seems to not being able to be downloaded:
```
--2021-02-02 15:29:04--  http://mdtraj.org/travis-ci-cache/sparta+.tar.Z
Resolving mdtraj.org (mdtraj.org)... 99.84.174.12, 99.84.174.67, 99.84.174.39, ...
Connecting to mdtraj.org (mdtraj.org)|99.84.174.12|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://mdtraj.org/travis-ci-cache/sparta+.tar.Z [following]
--2021-02-02 15:29:04--  https://mdtraj.org/travis-ci-cache/sparta+.tar.Z
Connecting to mdtraj.org (mdtraj.org)|99.84.174.12|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2021-02-02 15:29:04 ERROR 403: Forbidden.
```

It also seems to read `devtools/travis-ci/install_sparta.sh ` which seems to use travis specific variables like:
```
if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then return; fi
```

**Comment by sroet** [comment]
That failure seems to be external to this PR, so this one is ready for a review. For easy testing of the pip installation you can run 
```
pip install git+https://github.com/sroet/mdtraj.git@pin_numpy_during_build
```
inside your testing environments

**Comment by rmcgibbo** [comment]
Yeah, this looks good.

**Pull request merged**
