### PR TITLE
Fix issue #1535, simply removes "stride" factor from "chunk" in "iterload"

### PR DESCRIPTION
**Pull request by alberginia**
I think this would solve issue #1545

### CODE REVIEW

**Comment by rmcgibbo** [comment]
Can you add a test, and show that the test fails for the current code and passes for the new code?

**Comment by alberginia** [comment]
Hi Robert! I don't have experience with this but I tried to add one, maybe you can check if it makes sense. Greetings!

**Comment by rmcgibbo** [comment]
```

def test_iterload_chunk_dcd(get_fn):
    # Makes sure that the actual chunk size yielded by iterload corresponds to the number of
    # frames specified when calling it (for dcd files).
    file = get_fn("alanine-dipeptide-explicit.dcd")
    top = get_fn("alanine-dipeptide-explicit.pdb")

    skip_frames = 3
    frames_chunk = 2

    chunks = []
    for traj_chunk in md.iterload(file, top=top, stride=skip_frames, chunk=frames_chunk):
        eq(len(traj_chunk), frames_chunk)
        chunks.append(traj_chunk)
```

Here's a fixed version of the test that doesn't crash when loading the file.

**Comment by rmcgibbo** [comment]
However the test still does not appear to pass.

**Comment by rmcgibbo** [comment]
Thanks for fixing this. I cleaned up the test in #1549. If that passes I'll merge that and close this PR.

**Comment by rmcgibbo** [comment]
Fixed now.

**Pull request closed without merging**
