### PR TITLE
IPython viewer in docs

### PR DESCRIPTION
**Pull request by rmcgibbo**
This is a bit of a hack, but it's okay.

http://stanford.edu/~rmcgibbo/mdtraj/viewer.html

### CODE REVIEW

**Comment by cxhernandez** [comment]
it looks fine for a demo, i think

**Comment by mpharrigan** [comment]
It doesn't work on my laptop (windows, latest firefox). The protein is there to begin with, but if I click it goes away

**Comment by rmcgibbo** [comment]
does that also happen w/ the ipython notebook version, or just with this static view?

**Comment by mpharrigan** [comment]
yeah doesn't work through ipynotebook either

**Comment by cxhernandez** [comment]
What does the JavaScript console say?

**Comment by mpharrigan** [comment]
```
"Kernel: kernel_connected (e70c2651-5955-4b98-859e-b161a3eed1d3)" kernel.js:98:12
"Kernel: kernel_ready (e70c2651-5955-4b98-859e-b161a3eed1d3)" kernel.js:98:12
"THREE.WebGLRenderer" "68" three.min.js:520:0

# Disappears here! Then after a long pause

"TrajectoryView.update" outputarea.js:63:12
Object { fileName: "http://localhost:8888/static/base/js/utils.js?v=20150406174014", lineNumber: 697, columnNumber: 18, stack: "WrappedError@http://localhost:8888/static/base/js/utils.js?v=20150406174014:697:19
reject/<@http://localhost:8888/static/base/js/utils.js?v=20150406174014:776:33
", message: "Could not get state of widget manager", error_stack: Array[3] } utils.js:777:21
reject/<() utils.js:777

Object { fileName: "http://localhost:8888/static/base/js/utils.js?v=20150406174014", lineNumber: 697, columnNumber: 18, stack: "WrappedError@http://localhost:8888/static/base/js/utils.js?v=20150406174014:697:19
reject/<@http://localhost:8888/static/base/js/utils.js?v=20150406174014:776:33
", message: "Could not call widget save state callback.", error_stack: Array[3] } utils.js:777:21
reject/<() utils.js:777

Error: Could not call widget save state callback. utils.js:697:18
```

**Comment by cxhernandez** [comment]
No idea. Sounds like it's looking for the IPython widget or something, but not sure why that would only show up on Firefox :-/

**Comment by rmcgibbo** [comment]
It worked for me in FF on ubuntu and os-x. I'm going to merge this now, since the windows error doesn't seem related to this PR in particular.

**Pull request merged**
