### PR TITLE
Update CentOS 5 instructions

### PR DESCRIPTION
**Pull request by mpharrigan**
cc #749

### CODE REVIEW

**Comment by mpharrigan** [comment]
I don't know what the exact error message was. I don't want to re-compile a broken installation to find out

**Comment by rmcgibbo** [comment]
Why doesn't conda help here?

**Comment by kyleabeauchamp** [comment]
I think my VM is centos 6, not centos 5.  It's hard to get backwards compatability that far back AFAIK

**Comment by rmcgibbo** [comment]
Oh, the centos 5 thing is a glibc issue, right.

**Pull request merged**
