### PR TITLE
ENH: Add save_gro

### PR DESCRIPTION
**Pull request by mpharrigan**
cc #599

### CODE REVIEW

**Comment by mpharrigan** [comment]
wt2

VMD refuses to load the saved file unless I delete the trailing 6 box vector specifications, and then it looks crazy

**Comment by mpharrigan** [comment]
For > 100k atoms, gromacs seems to drop the first digit of atom id, and vmd is ok with that. mdtraj expands the column to 6 characters which messes everything up

**Comment by mpharrigan** [comment]
Added truncation

**Comment by rmcgibbo** [comment]
lgtm.

**Comment by rmcgibbo** [comment]
> VMD refuses to load the saved file unless I delete the trailing 6 box vector specifications, and then it looks crazy

Does this mean something is wrong?

**Comment by mpharrigan** [comment]
With the indexing fix that should now read: "VMD refuses to load the saved file unless I delete the trailing 6 box vector specifications, and then it looks fine"

The gro format spec I found said that those six values should be legit. I don't know why VMD has a problem with them

**Comment by rmcgibbo** [comment]
Okay, merging then.

**Pull request merged**
