### PR TITLE
Release v1.9.2

### PR DESCRIPTION
**Pull request by cxhernandez**
re: https://github.com/mdtraj/mdtraj/issues/1362

### CODE REVIEW

**Comment by cxhernandez** [comment]
@mdtraj/developers: Are we just ignoring the appveyor errors? Seems like there's an issue with PyTables not being installed.

**Comment by marscher** [comment]
@cxhernandez I think we can ignore it, the issue is unrelated an being handled here: https://github.com/conda-forge/pytables-feedstock/issues/31

**Comment by marscher** [comment]
#1375 seems to cure the pytables blosc issues. So we should conditionally depend on snappy for windows systems in the conda-forge recipe.

**Comment by marscher** [comment]
I guess you can now safely release 1.9.2, right?

**Pull request merged**
