### PR TITLE
[ENH] prmtop loader: add support for CHARMM (Chamber) topologies

### PR DESCRIPTION
**Pull request by swails**
This adds support for chamber prmtops and even speeds up prmtop parsing by 10-20% with simple optimizations.

### CODE REVIEW

**Comment by rmcgibbo** [comment]
do you have a simple chamber-style prmtop for something like ala2 that we can add as a test? (the file from @apeck12 is 2.3 megs.)

**Comment by swails** [comment]
I had ala3 on hand.  Test added.

**Comment by rmcgibbo** [comment]
that looks perfect.

**Comment by rmcgibbo** [comment]
tested locally. merging.

**Pull request merged**
