### PR TITLE
add missing type conversion in image_molecules before calling C code

### PR DESCRIPTION
**Pull request by fabian-paul**
Fixes "ValueError: Buffer dtype mismatch, expected 'int32_t'" but got 'long' in mdtraj.geometry._geometry.image_frame.

### CODE REVIEW

**Comment by poonampandey05** [comment]
Still getting the same error with mdtraj 1.9.3

**Comment by marscher** [comment]
could you please share a piece of code triggering the error?

**Comment by poonampandey05** [comment]
The code is as follow:
from __future__ import print_function, division
import mdtraj as md

t = md.load('d1le3.new_1le3.1.dcd', top='../step2_drude.psf')
protein = t.topology.guess_anchor_molecules()
newtraj = t.image_molecules(anchor_molecules=protein)

**Comment by fabian-paul** [comment]
This bugfix isn't in the 1.9.3 release. I think you have to install from github.

**Pull request merged**
