### PR TITLE
Fix windows python3 appveyor error

### PR DESCRIPTION
**Pull request by rmcgibbo**
Seems to be a segfault anytimes pytables interacts with a BLOSC-compressed file on windows py3, so I regenerated two very old reference files, and skipped the lh5 tests on win py3. cc #912

### CODE REVIEW

**Comment by mpharrigan** [comment]
Is this still relevant? Probably could use a rebase or two

**Comment by rmcgibbo** [comment]
Okay I think this is fixed, by rooting out all of the BLOSC-compressed files from the tests basically.

**Comment by rmcgibbo** [comment]
@mpharrigan can you apply https://github.com/msmbuilder/msmbuilder/pull/650 to this repo too?

**Comment by mpharrigan** [comment]
Sure. I'll do it tomorrow

**Comment by rmcgibbo** [comment]
IIRC, there's one issue here that I don't understand where on certain versions of Python, the DSSP tests hang or segfault or something, and I think it's somewhat random.

**Comment by rmcgibbo** [comment]
But otherwise, this should probably be merged.

**Comment by mpharrigan** [comment]
+1

**Pull request merged**
