### PR TITLE
Added TrajectorySliderView

### PR DESCRIPTION
**Pull request by cxhernandez**
As discussed in https://github.com/mdtraj/mdtraj/issues/863

### CODE REVIEW

**Comment by rmcgibbo** [comment]
are you supposed to call `display` inside the function?

**Comment by cxhernandez** [comment]
@rmcgibbo: I made `TrajectorySliderView` a function (which returns a TrajectoryView class), but I'm not sure if you had imagined each one of these as a separate class.

**Comment by cxhernandez** [comment]
It works in my notebook.... Is there something wrong with calling display?

**Comment by rmcgibbo** [comment]
`display` essentially called automatically on the return value of each cell in the notebook.

**Comment by cxhernandez** [comment]
> display essentially called automatically on the return value of each cell in the notebook

Not sure I follow. Are you saying it's unnecessary, since I'm returning the `TrajectoryView ` object?

**Comment by rmcgibbo** [comment]
I don't entirely remember how this IPython API works. But basically, I think having the library call `display` is not the correct usage, even if it does work. I think we should be returning some kind of container.

**Comment by cxhernandez** [comment]
Ah, I found an example [here](https://books.google.com/books?id=yZafBAAAQBAJ&pg=PT207&lpg=PT207&dq=ipython+widget+container&source=bl&ots=vVk32QMXP_&sig=z-eASvffRP-1UFF-RZi6S2W3cR4&hl=en&sa=X&ved=0CE0Q6AEwB2oVChMI4L3DxLyGxgIVUi6ICh3ssABQ#v=onepage&q=ipython%20widget%20container&f=false)

**Comment by cxhernandez** [comment]
Though `ContainerWidget` is apparently deprecated as well...

**Comment by mpharrigan** [comment]
Nice commit emoji

**Comment by cxhernandez** [comment]
silly windows. Is this okay to merge?

**Comment by rmcgibbo** [comment]
Don't be delayed on my behalf. Whoever else can hit the merge button if
it's ready.

**Pull request merged**
