### PR TITLE
Retrigger CI

### PR DESCRIPTION
**Pull request by rmcgibbo**

### CODE REVIEW

**Comment by rmcgibbo** [comment]
@marscher do we still need all the MDTRAJ_TEST_PEP517 business?

**Comment by marscher** [comment]
Yes, with this var ee can trigger pip builds within conda build. 

Am 6. Mai 2019 21:33:15 MESZ schrieb "Robert T. McGibbon" <notifications@github.com>:
>@marscher do we still need all the MDTRAJ_TEST_PEP517 business?

**Comment by rmcgibbo** [comment]
```

Traceback (most recent call last):
  File "/home/travis/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/travis/miniconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 456, in main
    execute(sys.argv[1:])
  File "/home/travis/miniconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 447, in execute
    verify=args.verify, variants=args.variants)
  File "/home/travis/miniconda3/lib/python3.7/site-packages/conda_build/api.py", line 208, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/home/travis/miniconda3/lib/python3.7/site-packages/conda_build/build.py", line 2314, in build_tree
    notest=notest,
  File "/home/travis/miniconda3/lib/python3.7/site-packages/conda_build/build.py", line 1324, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/home/travis/miniconda3/lib/python3.7/site-packages/conda_build/render.py", line 735, in expand_outputs
    for (output_dict, m) in _m.copy().get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "/home/travis/miniconda3/lib/python3.7/site-packages/conda_build/metadata.py", line 2038, in get_output_metadata_set
    bypass_env_check=bypass_env_check)
  File "/home/travis/miniconda3/lib/python3.7/site-packages/conda_build/metadata.py", line 721, in finalize_outputs_pass
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/home/travis/miniconda3/lib/python3.7/site-packages/conda_build/render.py", line 509, in finalize_metadata
    exclude_pattern)
  File "/home/travis/miniconda3/lib/python3.7/site-packages/conda_build/render.py", line 393, in add_upstream_pins
    permit_unsatisfiable_variants, exclude_pattern)
  File "/home/travis/miniconda3/lib/python3.7/site-packages/conda_build/render.py", line 359, in _read_upstream_pin_files
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/home/travis/miniconda3/lib/python3.7/site-packages/conda_build/render.py", line 143, in get_env_dependencies
    channel_urls=tuple(m.config.channel_urls))
  File "/home/travis/miniconda3/lib/python3.7/site-packages/conda_build/environ.py", line 755, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {'python=3.5', "openssl[version='>=1.1.1a,<1.1.2a']"}
The command "conda build --quiet devtools/conda-recipe && devtools/travis-ci/build_docs.sh" exited with 1.
```

@marscher: how do you feel about dropping python 3.5 from the test matrix?

**Comment by kyleabeauchamp** [comment]
FWIW, we've dropped py35 in conda-forge and Bioconda, so py35 is only going to get harder to maintain...

**Comment by rmcgibbo** [comment]
And it's not like this project is "flush" with engineering resources...

**Comment by rmcgibbo** [comment]
Pretty good progress! Linux is green and windows is good except for a conda issue on 2.7?

**Pull request merged**
