### PR TITLE
Cleanup in from_dataframe

### PR DESCRIPTION
**Pull request by kyleabeauchamp**

### CODE REVIEW

**Comment by synapticarbors** [comment]
When I pass in `bonds=np.zeros((2,0))`, I get an error locally:

```
df_top = pd.DataFrame({'serial': 0, 'name': 'SOD', 'element': 'Na', 'chainID': 0, 'resSeq': 1, 'resName': 'SOD'}, index=[0])
bonds = np.zeros((2, 0))
t = md.Topology.from_dataframe(df_top, bonds=bonds)
```

error:

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-53-8bf1577ac72f> in <module>()
      1 df_top = pd.DataFrame({'serial': 0, 'name': 'SOD', 'element': 'Na', 'chainID': 0, 'resSeq': 1, 'resName': 'SOD'}, index=[0])
      2 bonds = np.zeros((2, 0))
----> 3 t = md.Topology.from_dataframe(df_top, bonds=bonds)

/Users/lev/Documents/projects/github/mdtraj/mdtraj/core/topology.pyc in from_dataframe(cls, atoms, bonds)
    423 
    424         if bonds is not None:
--> 425             for ai1, ai2 in bonds:
    426                 out.add_bond(out.atom(ai1), out.atom(ai2))
    427 

ValueError: need more than 0 values to unpack
```

It would seem like it would make more sense just to check for `None`:

```
if not isinstance(bonds, np.ndarray) and bonds is not None:
    ...
```

**Comment by kyleabeauchamp** [comment]
My bad, swapped the order of (0, 2)...

**Comment by synapticarbors** [comment]
It works now. With that change, do you still want o check is `bonds` is `None` toward the end of the method if it can't actually be `None` by that point in the method execution?

**Comment by kyleabeauchamp** [comment]
Removed the redundant check, thanks

**Comment by rmcgibbo** [comment]
lgtm. will merge after travis.

**Pull request merged**
