### PR TITLE
drop distutils from tests

### PR DESCRIPTION
**Pull request by dotlambda**

### CODE REVIEW

**Review by ctk3b — APPROVED** [review]
LGTM - thank you!

For posterity, [distutils is deprecated with planned removal in python 3.12](https://docs.python.org/3.10/library/distutils.html)

**Comment by mattwthompson** [comment]
Something is wrong somewhere. Our CI has been running 3.12 for ages without this change. Maybe these tests aren't run, or these files aren't imported? Or this branch isn't up-to-date?

A recent CI matrix: https://github.com/mdtraj/mdtraj/actions/runs/10009432783/job/27668326834

A recent log: https://productionresultssa16.blob.core.windows.net/actions-results/b6e8a13e-1a3a-4bc4-abb9-66b8005147a8/workflow-job-run-4748b45f-36f3-52a4-b0b3-a862cf9444ab/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-08-20T13%3A24%3A23Z&sig=P2%2By0X7z3Wist%2BL%2Bg7A4vBAQ7h5OgOkH8jBeh5GrizU%3D&ske=2024-08-21T00%3A33%3A11Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-08-20T12%3A33%3A11Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-05-04&sp=r&spr=https&sr=b&st=2024-08-20T13%3A14%3A18Z&sv=2024-05-04

It looks like 3.12 is running

**Comment by jeremyleung521** [comment]
> Something is wrong somewhere. Our CI has been running 3.12 for ages without this change. Maybe these tests aren't run, or these files aren't imported? Or this branch isn't up-to-date?
> 
> A recent CI matrix: https://github.com/mdtraj/mdtraj/actions/runs/10009432783/job/27668326834
> 
> A recent log: https://productionresultssa16.blob.core.windows.net/actions-results/b6e8a13e-1a3a-4bc4-abb9-66b8005147a8/workflow-job-run-4748b45f-36f3-52a4-b0b3-a862cf9444ab/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-08-20T13%3A24%3A23Z&sig=P2%2By0X7z3Wist%2BL%2Bg7A4vBAQ7h5OgOkH8jBeh5GrizU%3D&ske=2024-08-21T00%3A33%3A11Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-08-20T12%3A33%3A11Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-05-04&sp=r&spr=https&sr=b&st=2024-08-20T13%3A14%3A18Z&sv=2024-05-04
> 
> It looks like 3.12 is running

`distutils` is vendored by `setuptools`, so either way works (with or without this PR). But I think the general trend is to shift away from distutils (e.g., https://github.com/pypa/pipx/issues/102), so I'm in favor of merging this.

**Comment by mattwthompson** [comment]
Good catch

**Review by mattwthompson — APPROVED** [review]
These are the only imports I find locally (at least in Python files)

**Pull request merged**
