### PR TITLE
changed removeNode -> remove_node 

### PR DESCRIPTION
**Pull request by schwancr**
to get rid of that annoying deprecation warning from pytables

### CODE REVIEW

**Comment by rmcgibbo** [comment]
http://mdtraj.org/latest/installation.html#dependencies says that we support pytables > 2.4.0.

**Comment by schwancr** [comment]
https://www.youtube.com/watch?v=l1dnqKGuezo

**Comment by rmcgibbo** [comment]
:)

**Comment by rmcgibbo** [comment]
Closed in favor of #817

**Pull request closed without merging**
