### PR TITLE
image_molecules in cython

### PR DESCRIPTION
**Pull request by mpharrigan**
On 11 frame of 82k atoms

before: 25.0 s
after: 2.8 s

I'm going to rebase and tidy a bit. Specifically, I don't think compiling in `geometry.cpp` is necessary here

### CODE REVIEW

**Comment by mpharrigan** [comment]
Ok, I just moved this code to be part of `mdtraj.geometry._geometry`

**Comment by mpharrigan** [comment]
This also addresses #1086

**Comment by mpharrigan** [comment]
- [ ] docstring update
 - [ ] move `guess_anchor_molecules` to `Topology`
 - [ ] add a couple tests

**Comment by jchodera** [comment]
Is this still in progress?

**Comment by mpharrigan** [comment]
Yes, I'd still like to do the unchecked things above

**Comment by jchodera** [comment]
What about grabbing the tests from #1183 and punting on the refactoring to move `guess_anchor_molecules` to a separate PR?

**Comment by jchodera** [comment]
Any thoughts on that idea, @mpharrigan?

**Comment by mpharrigan** [comment]
I'd rather just move the function now so we don't introduce an api we're immediately going to break. Do you want to make those changes off of this branch?

**Comment by jchodera** [comment]
> I'd rather just move the function now so we don't introduce an api we're immediately going to break. Do you want to make those changes off of this branch?

Guessing the anchor molecules is still an internal-only function, right? There's still no API exposure.

> Do you want to make those changes off of this branch?

Would you want me to bring in my optional argument support (to let the user specify anchor molecules) and tests from #1183 into here?

In thinking about why we still have a bound peptide bouncing all over the place, I realized that the [current behavior with multiple anchors](https://github.com/mdtraj/mdtraj/blob/master/mdtraj/core/trajectory.py#L1908-L1964) is probably actually what we need---to image the peptide to minimize the contact distance---so I'm not sure why it isn't working (unless it's somehow not picking up the peptide as an anchor).

**Comment by mpharrigan** [comment]
>Guessing the anchor molecules is still an internal-only function, right? There's still no API exposure.
Nope! as currently written, it's not prefaced with an underscore. I'd imagine users would want to use this function to (a) see what's being guessed as an anchor molecule, (b) start with the guess, tweak it a bit, and feed into imaging function

>Would you want me to bring in my optional argument support (to let the user specify anchor molecules)

I think this already includes this change. What arguments in particular?

**Comment by jchodera** [comment]
> I think this already includes this change. What arguments in particular?

You're right!

> edit: tests from #1183 appreciated!

OK, will create a PR to your repo branch with just the tests.

**Comment by jchodera** [comment]
Any chance you could merge from master or rebase first?

**Comment by mpharrigan** [comment]
Rebased

**Comment by jchodera** [comment]
Thanks! PR created: https://github.com/mpharrigan/mdtraj/pull/5

**Comment by jchodera** [comment]
Looks like the appveyor error is just an HTTP timeout:
```
Fetching package metadata: .....Error: HTTPError: 504 Server Error: GATEWAY_TIMEOUT: https://repo.continuum.io/pkgs/pro/win-32/
```

**Comment by mpharrigan** [comment]
thanks @jchodera !

**Pull request merged**
