### PR TITLE
ENH: Fix GRO parser for files with higher precision.

### PR DESCRIPTION
**Pull request by swails**
Also adds the ability to write with arbitrary precision.

Should address #864

### CODE REVIEW

**Comment by rmcgibbo** [comment]
Thanks, Jason. I'll try to come up with some good test cases later today
(I'm on the train now).

**Comment by swails** [comment]
The failure is a timeout on one of the branches.

> Thanks, Jason. I'll try to come up with some good test cases later today
> (I'm on the train now).

One test I'd like to add is a round-trip where I write a high-precision GRO file and try to read it back in.  If I find time, I'll add it, but I have a Telluride conference coming up on Sunday and I have to get ready for that (and come up with something to present on).

**Comment by rmcgibbo** [comment]
Yeah, don't worry about it, if you have other stuff to do. I can add the
test.

**Comment by swails** [comment]
Awesome, thanks!

**Comment by swails** [comment]
I took a break from my presentation and went ahead and added tests (which revealed a mistake I made in arbitrary precision writing support).  Should be fixed now, and the original v_error.gro file was added as a test.  This should be good to go.

**Pull request merged**
