### PR TITLE
Fix segment_id issues take 3

### PR DESCRIPTION
**Pull request by mpharrigan**
Based off of the first two commits of #1088 

@jchodera let me know what you think

### CODE REVIEW

**Comment by jchodera** [comment]
Thanks!

In cases like this, is it possible to refer to which `Topology` object (mdtraj or openmm) the function expects? Now that they are inequivalent, it's often ambiguous as to which one(s) is(are) supported:
```python
     Parameters
      ----------
     topology : topology
         The base topology
```

**Comment by mpharrigan** [comment]
The assumption is mdtraj.Topology. If you find cases where it expects something different, feel free to update the docstrings

**Comment by mpharrigan** [comment]
Looks like travis failure is unrelated

**Comment by jchodera** [comment]
I think you can just retrigger the build.

**Comment by jchodera** [comment]
Other parts of the code in the same file are very specific:
```
         Parameters
         ----------
         traj : MDTraj.Trajectory, optional, default=None
             If specified, use the first frame from this trajectory to
             set the unitcell information in the openmm topology.
```
Being vague in that particular function seems inconsistent with the rest of the documentation.

**Comment by mpharrigan** [comment]
Which function?

**Comment by jchodera** [comment]
Here: https://github.com/mdtraj/mdtraj/pull/1089/files#diff-ce95bbb0db9dbb5dce66ba686ed67f2dR80

This one also used to be both `OpenMM` and `MDTraj` `Topology` compatible but now seems only `MDTraj`: https://github.com/mdtraj/mdtraj/pull/1089/files#diff-ce95bbb0db9dbb5dce66ba686ed67f2dR214

There are probably a few others that are now only one or the other due to the divergence.

**Comment by rmcgibbo** [comment]
This lgtm

**Pull request merged**
