### PR TITLE
[ENH] Don't allow bare literals in selection expressions

### PR DESCRIPTION
**Pull request by mpharrigan**
- [x] write test
- [x] fix

### CODE REVIEW

**Comment by mpharrigan** [comment]
I don't think there's a way to do what we want with just pyparsing grammar. I added in checks in the ParseAction objects.

I can't figure out a way to fail on single keywords
```
select('dog')
```
Will still work, whereas

```
select('protein and dog')
```
will fail because the `and` tree can tell that literals are no good

**Comment by mpharrigan** [comment]
cc #728

**Comment by mpharrigan** [comment]
I added a special case.

For the record: @rmcgibbo and I discussed a more [elegant, convoluted] scheme wherein we would parse strings and numbers to subclasses whose `__bool__` method raises an exception

**Comment by rmcgibbo** [comment]
There also might be another way to solve this at the level of the grammar, by changing where literals are allowed to occur. But I don't think either @mpharrigan or myself understand the structure of the grammar well enough to do this reliably. This code is... nontrivial.

**Pull request merged**
