### PR TITLE
[ci] test against conda-forge channel, because it is used to release.

### PR DESCRIPTION
**Pull request by marscher**

### CODE REVIEW

**Comment by rmcgibbo** [comment]
It looks like two of the test/requires aren't available on conda-forge.

**Comment by marscher** [comment]
namely? These could be injected in run_test.py by invoking pip, this is not as clean as providing them in the recipe

**Comment by rmcgibbo** [comment]
```
Traceback (most recent call last):
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda_build/environ.py", line 685, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda/plan.py", line 461, in install_actions
    update_deps, pinned)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda/plan.py", line 631, in get_actions_for_dists
    pkgs = r.install(specs, installed, update_deps=update_deps)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 813, in install
    pkgs = self.solve(specs, returnall=returnall)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 853, in solve
    reduced_index = self.get_reduced_index(specs)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 374, in get_reduced_index
    specs, features = self.verify_specs(specs)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 300, in verify_specs
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound: 
  - openmm
  - shiftx2
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 388, in main
    execute(sys.argv[1:])
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 379, in execute
    verify=args.verify)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda_build/api.py", line 187, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1802, in build_tree
    notest=notest,
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1011, in build
    raise e
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1002, in build
    channel_urls=tuple(m.config.channel_urls))
  File "/home/travis/miniconda3/lib/python3.6/site-packages/conda_build/environ.py", line 687, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {'shiftx2', 'openmm'}
```

**Comment by marscher** [comment]
oh this is going to take a while :)

**Comment by rmcgibbo** [comment]
It might work if you add both the `omnia` and `conda-forge` channels, putting `conda-forge` with a higher priority.

**Comment by marscher** [comment]
On 11/13/2017 04:38 PM, Robert T. McGibbon wrote:
> It might work if you add both the |omnia| and |conda-forge| channels,
> putting |conda-forge| with a higher priority.
That's a good idea. Thanks!

**Comment by jchodera** [comment]
Why put conda-forge higher priority? That's not how omnia is meant to be used:

http://omnia.md

**Comment by marscher** [comment]
Shall we add another entry to the build/test matrix, which exclusively
uses omnia then?

I have proposed this change, because mdtraj is also available on
conda-forge, but is not tested against their packages.

**Comment by marscher** [comment]
I addition mdtraj is not being built on omnia any more. At least I can
not spot the latest release in the recipes repository.

**Comment by jchodera** [comment]
Ah! So these are optional dependencies (built only omnia right now) that MDTraj *can* use, but aren't essential for the core build. Testing on two branches sounds like a great idea.

**Comment by marscher** [comment]
python3.4 is not supported by conda-forge any more.

**Comment by marscher** [comment]
any idea, why this homebrew installation thingy fails?

**Comment by ctk3b** [comment]
Add this before the install:

`if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi`

**Pull request merged**
