### PR TITLE
[basesetup] copy contents of export_include and static lib to src tree.

### LINKED ISSUE #1117: [basesetup] StaticLib outputdir not correct for develop install mode
For libtheobald we need to point the output directory to the actual source tree instead of the build directory for mdtraj.capi to work. Currently the headers and static libs are being stored in the temporary build directory, so they can not be included properly if one only has a development version of mdtraj installed.

### PR DESCRIPTION
**Pull request by marscher**
Fixes #1117

### CODE REVIEW

**Comment by rmcgibbo** [comment]
Do you have any idea if the windows failure is related to this PR?

**Comment by marscher** [comment]
No it isn't. It fails with some distance calculation error.

**Comment by rmcgibbo** [comment]
Okay, let's keep an eye out for that one and see if it's recurring or stochastic.

**Comment by rmcgibbo** [comment]
(Thanks for the fix!)

**Pull request merged**
