### PR TITLE
Compute dihedral indices separately

### LINKED ISSUE #971: Separate dihedral indicies calculations from computing dihedrals
It would be nice to get dihedral indices by name *without* computing the dihedrals. There are some "private" lambdas `_get_indices_phi`, psi, omega that do this. For chi1, 2, 3 the logic is built into `compute_chi1` etc

### PR DESCRIPTION
**Pull request by mpharrigan**
fixes #971

### CODE REVIEW

**Comment by mpharrigan** [comment]
These should accept a topology instead of requiring a trajectory...

**Comment by mpharrigan** [comment]
Updated `_atom_sequence` to take a topology.

For backwards compatibility, it checks if the inputted object has a `topology` attribute

I did change the argument *name* to `top`, which would break kwargs. I don't think anyone would be using kwargs for this private function, but we can keep it as `traj` if others want

**Comment by mpharrigan** [comment]
I found a usage in pyemma here

https://github.com/markovmodel/PyEMMA/blob/9ac76ba4d0e983a9193b6666b8bed6b1228a0d56/pyemma/coordinates/data/featurizer.py#L52

Hopefully with this PR they can get rid of that code entirely

@marscher @franknoe

**Comment by franknoe** [comment]
thank you!

@gph82

Am 04/11/15 um 05:39 schrieb Matthew Harrigan:
>
> I found a usage in pyemma here
>
> https://github.com/markovmodel/PyEMMA/blob/9ac76ba4d0e983a9193b6666b8bed6b1228a0d56/pyemma/coordinates/data/featurizer.py#L52
>
> Hopefully with this PR they can get rid of that code entirely
>
> @marscher <https://github.com/marscher> @franknoe 
> <https://github.com/franknoe>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/mdtraj/mdtraj/pull/972#issuecomment-153570492>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by gph82** [comment]
Thanks, will take care of that


On 11/04/2015 10:17 AM, Frank Noe wrote:
> thank you!
> 
> @gph82
> 
> Am 04/11/15 um 05:39 schrieb Matthew Harrigan:
>>
>> I found a usage in pyemma here
>>
>>
> https://github.com/markovmodel/PyEMMA/blob/9ac76ba4d0e983a9193b6666b8bed6b1228a0d56/pyemma/coordinates/data/featurizer.py#L52
>>
>> Hopefully with this PR they can get rid of that code entirely
>>
>> @marscher <https://github.com/marscher> @franknoe
>> <https://github.com/franknoe>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mdtraj/mdtraj/pull/972#issuecomment-153570492>.
>>
> 
> 
> -- 
> 
> ----------------------------------------------
> Prof. Dr. Frank Noe
> Head of Computational Molecular Biology group
> Freie Universitaet Berlin
> 
> Phone: (+49) (0)30 838 75354
> Web: research.franknoe.de
> Mail: Arnimallee 6, 14195 Berlin, Germany
> ----------------------------------------------
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mdtraj/mdtraj/pull/972#issuecomment-153648548>.
> 

-- 
Dr. Guillermo Pérez-Hernández
Freie Universität Berlin
Institute for Mathematics
Arnimallee 6
D-14195 Berlin
tel       0049 30 838 75775
http://userpage.fu-berlin.de/gph82/
--

**Comment by mpharrigan** [comment]
Carlos why'd you merge this? The tests never ran. If they had, they would have revealed a bug!

**Comment by cxhernandez** [comment]
I could've sworn the Travis test had finished. My bad!

**Pull request merged**
