### PR TITLE
Improve load_frame to support partial loading

### PR DESCRIPTION
**Pull request by lambdalisue**
I'm not really sure if you guys like this approach but I think partial loading is fundamental feature so I would like to ask you to review.

While there are `load_frame` function and it seems @rmcgibbo is not comfortable to add `load_partial` function which I proposed in https://github.com/mdtraj/mdtraj/issues/1034, I decided to make `load_frame` function to support `slice` instance. So when `index` argument of `load_frame` is an instance of `slice`, it returns trajectories within the range specified by `slice`.

Note that I didn't touch docstrings while I'm not sure if this PR is acceptable. Let me know if this PR is acceptable then I'll modify docstrings (but sometime I feel that my English is not clear enough to explain things so I'd prefer you to write if possible...)
#### Usage

``` python
import mdtraj as md
t = md.load_frame('traj.h5', slice(10, 20, 2))
print(t)
# <mdtraj.Trajectory with 5 frames, 22 atoms>
```
#### Supported formats

Same formats as `load_frame` (single frame version) supports.

### CODE REVIEW

**Comment by lambdalisue** [comment]
Note: Even this PR is not acceptable. I think https://github.com/lambdalisue/mdtraj/commit/1a54ad4c41b2ed6aabc496d7c9fc558b4e199d89 is a bug so at least that commit should be merged.

**Comment by rmcgibbo** [comment]
I like this.

**Comment by rmcgibbo** [comment]
I need to think about the API a little bit more though. It becomes a little bit redundant between `frame` and `stride` for the `load_XXX` functions now, since both can encode a stride/step.

**Comment by lambdalisue** [comment]
Glad to hear ;-)

Yes. It is a bit redundant but it is required to keep backward compatibility...
Or maybe use `list` or `tuple` which indicate `(start, stop)` instead of using `slice` instance?

**Comment by rmcgibbo** [comment]
Maybe the ideal thing would be to have keyword arguments that were `start`, `stop`, and `stride`, defaulting to `None` and mimicking the semantics of `range()`.

**Comment by mpharrigan** [comment]
Neat!

I'm sure we'll be able to find an API that everyone is happy with. It seems a little strange that `load_frame` now might return multiple frames. What if we kept `load_frame` the same, and moved this to a function like `load_frames` (maybe with the start, stop, and stride parameters like @rmcgibbo suggested)

But besides mundane naming concerns, this would be great to have. And the bugfix is important too!

**Comment by lambdalisue** [comment]
I think there are two topics. API for `load_frame(s)` and API for `load_XXX`.

So what about

```python
# If I don't need to keep the order of argument, `stride` should go the last like
#def load_XXX(filename, atom_indices=None, start=None, stop=None, stride=None):
def load_XXX(filename, stride=None, atom_indices=None, start=None, stop=None):
    # brabrabra

def load_frames(filename, start, stop=None, stride=None, top=None, atom_indices=None, **kwargs):
    # brabrabra
    return load_XXX(...)

# OR

def load_frame(filename, index_or_start, stop=None, stride=None, top=None, atom_indices=None, **kwargs):
    # brabrabra
    return load_XXX(...)
```

**Comment by lambdalisue** [comment]
ping

**Comment by rmcgibbo** [comment]
Sry my phd. defense is tomorrow so I can't look at this now.

**Comment by swails** [comment]
Good luck! What's next?

**Comment by lambdalisue** [comment]
Wow. Good luck :-]

**Comment by rmcgibbo** [comment]
Starting at DESRES in nyc in about 2 weeks.

**Comment by hainm** [comment]
:+1:

**Comment by marscher** [comment]
Thats cool @rmcgibbo. All the best for your new job then!

**Comment by lambdalisue** [comment]
... so what do I need to do rest?

**Comment by cxhernandez** [comment]
@mpharrigan: bump

**Comment by mpharrigan** [comment]
Thought @rmcgibbo was going to share his thoughts on this one.

I like the api suggested https://github.com/mdtraj/mdtraj/pull/1060#issuecomment-188662053. I agree it's unfortunate that we (probably) can't order the arguments (`start`, `stop`, `stride`) in the `load_xxx` functions. Maybe we can do a deprecation cycle during which we force people to specify stride or atom_indices with a keyword argument (although I don't know how to check if an argument is passed positionaly or with a keyword)

Do you have any thoughts @cxhernandez ?

**Comment by mpharrigan** [comment]
To be clear, I like the signature where the first parameter is named `start` :)

**Comment by cxhernandez** [comment]
I actually would prefer a scheme where you input a range or slice for `load_xxx` and consolidate 3 kwargs into one. It seems cleaner and would let users have more control over how they load frames (e.g. I could load trajectories using `np.logspace` this way).

Backwards compatibility would still be an issue though....

**Comment by hainm** [comment]
I think just add `frame_indices` (like in `pytraj`)

```python
md.load(..., frame_indices=...)
```

it can be `range(0, 100, 10)` or random integer array or iterator.

**Comment by rmcgibbo** [comment]
This seems outdated. Feel free to re-open if I'm mistaken.

**Pull request closed without merging**
