### PR TITLE
[WIP] ReadTheDocs migration

### PR DESCRIPTION
**Pull request by sukritsingh**
Opening a WIP PR for the RTD migration! Early results are promising with building the docs! Some key points with so far: 
1. I haven't deleted any of the existing files in `docs` yet, simply added new ones, so some may be redundant/not useful after migration 
2. I've added the necessary YAML files and configured `conf.py` and `requirements.txt`
3. The `requirements.txt` file is fairly large and potentially bloated. It involves things like OpenMM, which I'm not entirely sure is useful, so open to discussions on ways to minimize.
4. The jupyter notebook examples don't compile yet, which was the Original concern with migrating to RTD, but they also don't compile in our [current docs](https://www.mdtraj.org/1.9.8.dev0/examples/hbonds.html) page. I may just try and build static notebook examples and link to them for folks?

I got the invite for RTD - will accept now and see if we can test this branch out!

### CODE REVIEW

**Comment by sukritsingh** [comment]
@mattwthompson Is there a way you can set the default branch to `rtd-migration` for now on the dashboard? I don't see any options for to set the branch being built (admittedly, I am new to the RTD dashboard, so I may be missing something).

This way we can test the docs building before merging

**Comment by mattwthompson** [comment]
There's a drop-down for this buried in the settings but it's not populated yet (another one of my projects lists all branches)

https://readthedocs.org/dashboard/mdtraj/edit/

image


I've also added PR previews (which might not go live until a merge) https://docs.readthedocs.io/en/stable/guides/pull-requests.html

**Comment by mattwthompson** [comment]
Nevermind, PR previews require webhook permissions https://docs.readthedocs.io/en/stable/integrations.html

**Comment by sukritsingh** [comment]
> There's a drop-down for this buried in the settings but it's not populated yet (another one of my projects lists all branches)

Yeah I saw this drop down but I see the same thing as your screenshot. Was hoping that we could see all the branches, but I don't know what that would take? Any idea?

Looks like I can just put in a new commit and it'll be fine?
```
Pull requests opened before enabling pull request builds will not trigger new builds automatically. Push a new commit to the pull request to trigger its first build.
```

**Comment by sukritsingh** [comment]
> Nevermind, PR previews require webhook permissions https://docs.readthedocs.io/en/stable/integrations.html

Ah dangit - how do we get those permissions lol

**Comment by mattwthompson** [comment]
And email to the right person I figure (John? Greg? Some other F@H folks I haven't met?) I'm not an admin in this org 🙃

**Comment by sukritsingh** [comment]
>  And email to the right person I figure (John? Greg? Some other F@H folks I haven't met?) I'm not an admin in this org 🙃

It would be either Greg or Xuhui Huang (from FAH, UW-Madison). Let me email him and cc you. 

In the meantime/alternative, I'm scared to risk merging but I don't know any other ways forward to test this 😓

**Comment by mattwthompson** [comment]
Merging PRs into the development head is relatively low-cost. I figure as a first pass just making sure some docs build locally would be fine (API docs and rST files with prose) and the other issues can be picked away in a couple of extra steps. I can double-check these changes later today

I've had relatively good experiences with RTD's off-the-shelf behavior with Sphinx, but I've also been lucky to work in infrastructure that's largely similar enough because of the cookiecutter starting point https://github.com/MolSSI/cookiecutter-cms

**Comment by sukritsingh** [comment]
> I figure as a first pass just making sure some docs build locally would be fine (API docs and rST files with prose) and the other issues can be picked away in a couple of extra steps. 

Yeah I've just been using sphinx and running `make html` in the `docs` directory - the output is found in `_build/index.html` as is the norm. That works for me well enough. The only thing I can't really test is the `.readthedocs.yaml` file locally. Everything else builds as expected with the environment described in `requirements.txt`

I'm not familiar with `prose` but I'm down to try that out if you have any info!

**Comment by mattwthompson** [comment]
Haha "prose" there isn't a tool, it's just a catch-all for files like this https://github.com/mdtraj/mdtraj/blob/master/docs/new_to_python.rst

**Comment by sukritsingh** [comment]
> Haha "prose" there isn't a tool, it's just a catch-all for files like this https://github.com/mdtraj/mdtraj/blob/master/docs/new_to_python.rst

Oh! Haha I've never heard that description before. That's good to know – TIL.

I've pushed some more commits so that we have properly displaying notebook pages now! They may need some cleanup but it's already a net improvement than before!

I think now that we both have admin access, we could try setting up the webhook for PR testing? I've never setup a github webhook specifically before so I'm down to learn how, but I defer to your expertise here

**Comment by sukritsingh** [comment]
Ayy PR preview success: https://mdtraj--1888.org.readthedocs.build/en/1888/

**Comment by mattwthompson** [comment]
Awesome! That's my favorite RTD feature

**Comment by sukritsingh** [comment]
Alright - I've added a docs status badge to the README and it looks like everything is stable, and we build the docs in CI now, which addresses #1809 directly I believe, and advances #1810  

Feel free to take a look at the docs and suggest edits, but I've changed nothing except adding properly rendering the notebooks.

**Review by mattwthompson — APPROVED** [review]
The docs need some love ([oof](https://mdtraj--1888.org.readthedocs.build/en/1888/new_to_python.html#installing-python)) but the objective here IMO is to get docs built and I see this as a rousing success: https://mdtraj--1888.org.readthedocs.build/en/1888/new_to_python.html#installing-python

> I'm assuming that

Haha ... the "stable" branch/tag is always a thorn in my side. We use a [workflow](https://github.com/openforcefield/openff-toolkit/actions/workflows/release.yml) to do this at release time since I always screw it up (2.5 in https://github.com/openforcefield/openff-toolkit/issues/286).

**Comment by sukritsingh** [comment]
> The docs need some love ([oof](https://mdtraj--1888.org.readthedocs.build/en/1888/new_to_python.html#installing-python)) but the objective here IMO is to get docs built

Haha yea I didn't do a full audit of the docs or anything. I just got them to a "buildable" state – I figure the docs update/audit would be a separate PR for the sake of modulation.

I pushed a quick commit to address that `3.5` that you pointed to - just to make sure we don't cause further confusion.

Once the docs rebuild I'm happy to merge in!

> the "stable" branch/tag is always a thorn in my side. We use a [workflow](https://github.com/openforcefield/openff-toolkit/actions/workflows/release.yml) to do this at release time since I always screw it up

 I'm happy if we want to pick another tag or something on RTD to merge in. There's also `latest` which is what I included this time around for easy copying....

**Comment by sukritsingh** [comment]
Huzzah! `latest` build is passing! https://mdtraj.readthedocs.io/en/latest/

Now to just figure out how to build it to `https://mdtraj.readthedocs.io` (which I guess is the `stable` version?) Still figuring out what that means here – we could perhaps use a similar workflow for release time?

**Comment by janash** [comment]
For adding Jupyter notebooks to docs, I've used MyST NB with a lot of success - https://myst-nb.readthedocs.io/en/latest/

It uses MyST parser (which I also love). I'd highly recommend using this, as it allows you to add a Jupyter notebook to your table of contents the same way an `rst` or `md` file would be added.

**Pull request merged**
