### PR TITLE
Fix issue #1301

### PR DESCRIPTION
**Pull request by tverho**
https://github.com/mdtraj/mdtraj/issues/1301

### CODE REVIEW

**Comment by rmcgibbo** [comment]
Could you add a test case too?

**Comment by tverho** [comment]
I don't have a development environment to run the tests for latest master. Cython 0.29 is required, I have older.

**Comment by rmcgibbo** [comment]
Could you maybe attach and example file that fails with the current master branch but would work with the fix, if you have one? I can do the mechanics of testing it

**Comment by tverho** [comment]
Here's a .gro file with 1M particles. I don't have a topology because I deal with united atom polymers (the particles are all the same type).

IIRC the problem shows so that the serial field becomes wider than in the specification after 200k particles leading to an invalid file.

[polymer_melt.gro.zip](https://github.com/mdtraj/mdtraj/files/3787458/polymer_melt.gro.zip)

**Pull request merged**
