### PR TITLE
Fixed bugs in backbone and sidechain selection

### PR DESCRIPTION
**Pull request by synapticarbors**
This PR fixes the bugs reported in https://github.com/mdtraj/mdtraj/issues/695

Also, when I tried to install mdtraj from source using `python setup.py develop` in a conda environment, I was getting a message that `mdtraj` was not installed, even after the install process looked ok. Do other devs use this method of working on mdtraj? This is how I've worked with MSMBuilder recently and there everything works as expected.

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
For most of my packages, I've been avoiding `develop` in favor of forcing installs.  

To me, the issue with `develop` is that it makes it harder to guarantee that your a testing the same environment that end-users will see.

For example, for many of the projects I now do testing via `conda-build devtools/conda-recipe`, which creates a clean test environment and runs the nosetests outside of the source tree.  I agree that there are pros and cons with either way.

**Comment by kyleabeauchamp** [comment]
LGTM

**Comment by synapticarbors** [comment]
What I ended up doing was pretty similar actually, although more manual:

```
conda create -n mdtraj-test python cython numpy setuptools scipy pandas ipython nose
python setup.py install
```

The only problem is that when there is a small typo that needs to be corrected, you have to basically re-run everything which is pretty slow and makes iterating on problems difficult. Further, because of the twidling that setup.py does with names and script locations, you can't easily import mdtraj from the source tree without an install (although maybe there is an easy way to do this). 

It might be nice to add something to the docs about setting up a dev environment.

**Comment by rmcgibbo** [comment]
I usually use `setup.py develop`, and haven't had too many problems. Sometimes its a little flakey, and interacts poorly with versions installed in site-packages.

**Comment by synapticarbors** [comment]
@rmcgibbo strange that `setup.py develop` wasn't working for me with a clean conda environment:

```
git clone https://github.com/mdtraj/mdtraj.git mdtraj2
cd mdtraj2/
conda create -n mdtraj-test2 python ipython numpy pandas scipy nose cython
source activate mdtraj-test2
python setup.py develop
```

with the output of the last command ending with:

```
...
Creating /Users/lev/anaconda/envs/mdtraj-test2/lib/python2.7/site-packages/mdtraj.egg-link (link to .)
Adding mdtraj 1.3.0.dev0 to easy-install.pth file
Installing mdinspect script to /Users/lev/anaconda/envs/mdtraj-test2/bin
Installing mdconvert script to /Users/lev/anaconda/envs/mdtraj-test2/bin

Installed /Users/lev/Documents/projects/github/mdtraj2
Processing dependencies for mdtraj==1.3.0.dev0
Finished processing dependencies for mdtraj==1.3.0.dev0
```

Then trying to import mdtraj:

```
(mdtraj-test2) $ python -c "import mdtraj"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named mdtraj
```

The same exact procedure works fine with MSMBuilder on the same machine.

**Comment by rmcgibbo** [comment]
Try `mv MDTraj mdtraj` from the root project directory.

**Comment by synapticarbors** [comment]
@rmcgibbo ok, that fixed things. Thanks

**Comment by rmcgibbo** [comment]
I'll look at trying to fix this in the repo.

**Pull request merged**
