### PR TITLE
ENH: Enable .lammpstrj to parse custom column orders

### PR DESCRIPTION
**Pull request by ctk3b**
Users can technically [customize lammps trajectories](http://lammps.sandia.gov/doc/dump.html) to contain any information in any order. This PR removes any assumptions about column ordering.

### CODE REVIEW

**Comment by rmcgibbo** [comment]
Do you have any small files laying around using a custom / nonstandard header that we can add as a test?

**Comment by ctk3b** [comment]
I added one. However, there's a unit issue. I think you may have been correct about a unit bug in #845  afterall. I'm about to get on a plane but hopefully #844 fixes that. Sorry about that. Looking back on how I organized that unit conversion code is quite painful...

**Comment by rmcgibbo** [comment]
I restarted the build on master after merging #844.

**Comment by ctk3b** [comment]
Looks fixed. Thank you!

**Pull request merged**
