### PR TITLE
Add posonlyargs argument for Python 3.8 compatibility

### PR DESCRIPTION
**Pull request by mattwthompson**
Just seeing if the proposal in https://github.com/mdtraj/mdtraj/issues/1509 passes CI. This passes locally this locally in a 3.7 environment, which is encouraging.

### CODE REVIEW

**Comment by rmcgibbo** [comment]
Seems reasonable to merge, right?

**Comment by mattwthompson** [comment]
This is parts of the codebase (and standard library) I'm not familiar with, so I'm not sure if there's some behavior not covered by tests. But CI is passing and it seems like this is a straightforward enough patch, so I think so.

**Comment by rmcgibbo** [comment]
We’re you able to test it on 3.8 and see that it fixed the observed issues?

**Comment by mattwthompson** [comment]
Well, that's embarrassing - one test was failing locally and I thought I'd try CI anyway. Of course I forgot it's not running on 3.8.

This change fixes that for me locally - at least `test_selection.py`, which passes in my 3.7 and 3.8 environments. Python 3.8 snuck in a `kind` field to `ast.Constant`. I thought about just having the tests compare `.value` but just passing `kind=None` to the constructor seemed like a better idea.

There are other failing tests in my 3.8 environment but they're all related to glue. Something for another day when people want to bump the version.

**Pull request merged**
