### PR TITLE
Fix gro loading for issue 721

### PR DESCRIPTION
**Pull request by synapticarbors**
This a fix that should address https://github.com/mdtraj/mdtraj/issues/721 and several other issues that weren't immediately obvious from the reported traceback.

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
I think this looks good.  Can you also fix the docstring in the `read()` function to match the mixed up return order.  E.g.

https://github.com/mdtraj/mdtraj/blob/master/mdtraj/formats/gro.py#L200

**Comment by synapticarbors** [comment]
@kyleabeauchamp or is it better to change the order of the return to keep with general convention? It's a little hard to tell if this is consistent across most formats. For instance for the `xtc` reader, `time` comes before box info.

**Comment by synapticarbors** [comment]
Actually, looking through the different readers `time` always is returned before box info, so I'll change the return order rather than the docstring.

**Comment by kyleabeauchamp** [comment]
Either way sounds good to me.

**Comment by kyleabeauchamp** [comment]
LGTM

**Pull request merged**
