### PR TITLE
Correct hoomdxml ordering

### PR DESCRIPTION
**Pull request by ahy3nz**
Addresses #1389. The original issue was the order in which the atoms were being added - first were the chains and then the non-bonded particles. As a result, the ordering in the `mdtraj.Topology` would likely be incorrect. This PR adjusts the reading/iteration to look sequentially through the hoomdxml file, generating or finding the relevant chains/residues, and then adding the atom to the Topology.

### CODE REVIEW

**Comment by rmcgibbo** [comment]
Thanks for fixing this!

I rebooted one of the travis workers that timed out. Not sure what's wrong with the Windows CI, but it's definitely not your fault:

```

Executing: conda build --quiet devtools\conda-recipe
Traceback (most recent call last):
  File "C:\Miniconda36-x64\Scripts\conda-build-script.py", line 6, in <module>
    from conda_build.cli.main_build import main
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\cli\main_build.py", line 19, in <module>
    import conda_build.build as build
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\build.py", line 61, in <module>
    from conda_build import environ, source, tarcheck, utils
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\environ.py", line 29, in <module>
    from conda_build.index import get_build_index
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\index.py", line 45, in <module>
    from conda.core.subdir_data import SubdirData
ModuleNotFoundError: No module named 'conda.core.subdir_data'
```
:nauseated_face:

**Comment by ahy3nz** [comment]
It looks like something weird is still happening with appveyor and I'm not entirely sure

**Comment by rmcgibbo** [comment]
I poked the appveyor one more time and it seems to have run okay for one of the three tests.

**Comment by rmcgibbo** [comment]
Looks green!

**Pull request merged**
